// Code generated by protoc-gen-go. DO NOT EDIT.
// source: quotes/quotes.proto

package quotes

import (
	context "context"
	fmt "fmt"
	math "math"

	"github.com/Beaxhem/manage/backend/internal/products"
	"github.com/Beaxhem/manage/backend/internal/services"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_NEW               Status = 0
	Status_SUPPLIER_APPLIED  Status = 1
	Status_CLIENT_APPLIED    Status = 2
	Status_PREPARATION       Status = 3
	Status_PRODUCTION        Status = 4
	Status_DELIVERED         Status = 5
	Status_COMPLETED         Status = 6
	Status_CANCELLED         Status = 7
	Status_SUPPLIER_REJECTED Status = 8
	Status_CLIENT_REJECTED   Status = 9
)

var Status_name = map[int32]string{
	0: "NEW",
	1: "SUPPLIER_APPLIED",
	2: "CLIENT_APPLIED",
	3: "PREPARATION",
	4: "PRODUCTION",
	5: "DELIVERED",
	6: "COMPLETED",
	7: "CANCELLED",
	8: "SUPPLIER_REJECTED",
	9: "CLIENT_REJECTED",
}

var Status_value = map[string]int32{
	"NEW":               0,
	"SUPPLIER_APPLIED":  1,
	"CLIENT_APPLIED":    2,
	"PREPARATION":       3,
	"PRODUCTION":        4,
	"DELIVERED":         5,
	"COMPLETED":         6,
	"CANCELLED":         7,
	"SUPPLIER_REJECTED": 8,
	"CLIENT_REJECTED":   9,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_15679ebe12a64146, []int{0}
}

type QuoteResponse struct {
	Quotes               []*Quote `protobuf:"bytes,1,rep,name=quotes,proto3" json:"quotes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuoteResponse) Reset()         { *m = QuoteResponse{} }
func (m *QuoteResponse) String() string { return proto.CompactTextString(m) }
func (*QuoteResponse) ProtoMessage()    {}
func (*QuoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15679ebe12a64146, []int{0}
}

func (m *QuoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuoteResponse.Unmarshal(m, b)
}
func (m *QuoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuoteResponse.Marshal(b, m, deterministic)
}
func (m *QuoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuoteResponse.Merge(m, src)
}
func (m *QuoteResponse) XXX_Size() int {
	return xxx_messageInfo_QuoteResponse.Size(m)
}
func (m *QuoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuoteResponse proto.InternalMessageInfo

func (m *QuoteResponse) GetQuotes() []*Quote {
	if m != nil {
		return m.Quotes
	}
	return nil
}

type QuoteParams struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Jwt                  string   `protobuf:"bytes,2,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuoteParams) Reset()         { *m = QuoteParams{} }
func (m *QuoteParams) String() string { return proto.CompactTextString(m) }
func (*QuoteParams) ProtoMessage()    {}
func (*QuoteParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_15679ebe12a64146, []int{1}
}

func (m *QuoteParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuoteParams.Unmarshal(m, b)
}
func (m *QuoteParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuoteParams.Marshal(b, m, deterministic)
}
func (m *QuoteParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuoteParams.Merge(m, src)
}
func (m *QuoteParams) XXX_Size() int {
	return xxx_messageInfo_QuoteParams.Size(m)
}
func (m *QuoteParams) XXX_DiscardUnknown() {
	xxx_messageInfo_QuoteParams.DiscardUnknown(m)
}

var xxx_messageInfo_QuoteParams proto.InternalMessageInfo

func (m *QuoteParams) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *QuoteParams) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

type Response struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_15679ebe12a64146, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type StatusParams struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusParams) Reset()         { *m = StatusParams{} }
func (m *StatusParams) String() string { return proto.CompactTextString(m) }
func (*StatusParams) ProtoMessage()    {}
func (*StatusParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_15679ebe12a64146, []int{3}
}

func (m *StatusParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusParams.Unmarshal(m, b)
}
func (m *StatusParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusParams.Marshal(b, m, deterministic)
}
func (m *StatusParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusParams.Merge(m, src)
}
func (m *StatusParams) XXX_Size() int {
	return xxx_messageInfo_StatusParams.Size(m)
}
func (m *StatusParams) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusParams.DiscardUnknown(m)
}

var xxx_messageInfo_StatusParams proto.InternalMessageInfo

func (m *StatusParams) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *StatusParams) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Stats struct {
	Active               uint32   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Pending              uint32   `protobuf:"varint,2,opt,name=pending,proto3" json:"pending,omitempty"`
	Denied               uint32   `protobuf:"varint,3,opt,name=denied,proto3" json:"denied,omitempty"`
	New                  uint32   `protobuf:"varint,4,opt,name=new,proto3" json:"new,omitempty"`
	Applied              uint32   `protobuf:"varint,5,opt,name=applied,proto3" json:"applied,omitempty"`
	Preparation          uint32   `protobuf:"varint,6,opt,name=preparation,proto3" json:"preparation,omitempty"`
	Production           uint32   `protobuf:"varint,7,opt,name=production,proto3" json:"production,omitempty"`
	Delivered            uint32   `protobuf:"varint,10,opt,name=delivered,proto3" json:"delivered,omitempty"`
	Completed            uint32   `protobuf:"varint,12,opt,name=completed,proto3" json:"completed,omitempty"`
	Cancelled            uint32   `protobuf:"varint,13,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stats) Reset()         { *m = Stats{} }
func (m *Stats) String() string { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()    {}
func (*Stats) Descriptor() ([]byte, []int) {
	return fileDescriptor_15679ebe12a64146, []int{4}
}

func (m *Stats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stats.Unmarshal(m, b)
}
func (m *Stats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stats.Marshal(b, m, deterministic)
}
func (m *Stats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stats.Merge(m, src)
}
func (m *Stats) XXX_Size() int {
	return xxx_messageInfo_Stats.Size(m)
}
func (m *Stats) XXX_DiscardUnknown() {
	xxx_messageInfo_Stats.DiscardUnknown(m)
}

var xxx_messageInfo_Stats proto.InternalMessageInfo

func (m *Stats) GetActive() uint32 {
	if m != nil {
		return m.Active
	}
	return 0
}

func (m *Stats) GetPending() uint32 {
	if m != nil {
		return m.Pending
	}
	return 0
}

func (m *Stats) GetDenied() uint32 {
	if m != nil {
		return m.Denied
	}
	return 0
}

func (m *Stats) GetNew() uint32 {
	if m != nil {
		return m.New
	}
	return 0
}

func (m *Stats) GetApplied() uint32 {
	if m != nil {
		return m.Applied
	}
	return 0
}

func (m *Stats) GetPreparation() uint32 {
	if m != nil {
		return m.Preparation
	}
	return 0
}

func (m *Stats) GetProduction() uint32 {
	if m != nil {
		return m.Production
	}
	return 0
}

func (m *Stats) GetDelivered() uint32 {
	if m != nil {
		return m.Delivered
	}
	return 0
}

func (m *Stats) GetCompleted() uint32 {
	if m != nil {
		return m.Completed
	}
	return 0
}

func (m *Stats) GetCancelled() uint32 {
	if m != nil {
		return m.Cancelled
	}
	return 0
}

type QuoteProduct struct {
	Product              *products.Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Qty                  uint32            `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`
	Sizel                float32           `protobuf:"fixed32,3,opt,name=sizel,proto3" json:"sizel,omitempty"`
	Sizew                float32           `protobuf:"fixed32,4,opt,name=sizew,proto3" json:"sizew,omitempty"`
	Sizeh                float32           `protobuf:"fixed32,5,opt,name=sizeh,proto3" json:"sizeh,omitempty"`
	Sizer                float32           `protobuf:"fixed32,6,opt,name=sizer,proto3" json:"sizer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *QuoteProduct) Reset()         { *m = QuoteProduct{} }
func (m *QuoteProduct) String() string { return proto.CompactTextString(m) }
func (*QuoteProduct) ProtoMessage()    {}
func (*QuoteProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_15679ebe12a64146, []int{5}
}

func (m *QuoteProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuoteProduct.Unmarshal(m, b)
}
func (m *QuoteProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuoteProduct.Marshal(b, m, deterministic)
}
func (m *QuoteProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuoteProduct.Merge(m, src)
}
func (m *QuoteProduct) XXX_Size() int {
	return xxx_messageInfo_QuoteProduct.Size(m)
}
func (m *QuoteProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_QuoteProduct.DiscardUnknown(m)
}

var xxx_messageInfo_QuoteProduct proto.InternalMessageInfo

func (m *QuoteProduct) GetProduct() *products.Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *QuoteProduct) GetQty() uint32 {
	if m != nil {
		return m.Qty
	}
	return 0
}

func (m *QuoteProduct) GetSizel() float32 {
	if m != nil {
		return m.Sizel
	}
	return 0
}

func (m *QuoteProduct) GetSizew() float32 {
	if m != nil {
		return m.Sizew
	}
	return 0
}

func (m *QuoteProduct) GetSizeh() float32 {
	if m != nil {
		return m.Sizeh
	}
	return 0
}

func (m *QuoteProduct) GetSizer() float32 {
	if m != nil {
		return m.Sizer
	}
	return 0
}

type ServiceInQuote struct {
	Service              *services.Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Qty                  uint32            `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ServiceInQuote) Reset()         { *m = ServiceInQuote{} }
func (m *ServiceInQuote) String() string { return proto.CompactTextString(m) }
func (*ServiceInQuote) ProtoMessage()    {}
func (*ServiceInQuote) Descriptor() ([]byte, []int) {
	return fileDescriptor_15679ebe12a64146, []int{6}
}

func (m *ServiceInQuote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceInQuote.Unmarshal(m, b)
}
func (m *ServiceInQuote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceInQuote.Marshal(b, m, deterministic)
}
func (m *ServiceInQuote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceInQuote.Merge(m, src)
}
func (m *ServiceInQuote) XXX_Size() int {
	return xxx_messageInfo_ServiceInQuote.Size(m)
}
func (m *ServiceInQuote) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceInQuote.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceInQuote proto.InternalMessageInfo

func (m *ServiceInQuote) GetService() *services.Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *ServiceInQuote) GetQty() uint32 {
	if m != nil {
		return m.Qty
	}
	return 0
}

type Suppliers struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Suppliers) Reset()         { *m = Suppliers{} }
func (m *Suppliers) String() string { return proto.CompactTextString(m) }
func (*Suppliers) ProtoMessage()    {}
func (*Suppliers) Descriptor() ([]byte, []int) {
	return fileDescriptor_15679ebe12a64146, []int{7}
}

func (m *Suppliers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Suppliers.Unmarshal(m, b)
}
func (m *Suppliers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Suppliers.Marshal(b, m, deterministic)
}
func (m *Suppliers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Suppliers.Merge(m, src)
}
func (m *Suppliers) XXX_Size() int {
	return xxx_messageInfo_Suppliers.Size(m)
}
func (m *Suppliers) XXX_DiscardUnknown() {
	xxx_messageInfo_Suppliers.DiscardUnknown(m)
}

var xxx_messageInfo_Suppliers proto.InternalMessageInfo

func (m *Suppliers) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Suppliers) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

type Distance struct {
	Distance             int32    `protobuf:"varint,1,opt,name=distance,proto3" json:"distance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Distance) Reset()         { *m = Distance{} }
func (m *Distance) String() string { return proto.CompactTextString(m) }
func (*Distance) ProtoMessage()    {}
func (*Distance) Descriptor() ([]byte, []int) {
	return fileDescriptor_15679ebe12a64146, []int{8}
}

func (m *Distance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Distance.Unmarshal(m, b)
}
func (m *Distance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Distance.Marshal(b, m, deterministic)
}
func (m *Distance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Distance.Merge(m, src)
}
func (m *Distance) XXX_Size() int {
	return xxx_messageInfo_Distance.Size(m)
}
func (m *Distance) XXX_DiscardUnknown() {
	xxx_messageInfo_Distance.DiscardUnknown(m)
}

var xxx_messageInfo_Distance proto.InternalMessageInfo

func (m *Distance) GetDistance() int32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

type DistanceParams struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DistanceParams) Reset()         { *m = DistanceParams{} }
func (m *DistanceParams) String() string { return proto.CompactTextString(m) }
func (*DistanceParams) ProtoMessage()    {}
func (*DistanceParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_15679ebe12a64146, []int{9}
}

func (m *DistanceParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistanceParams.Unmarshal(m, b)
}
func (m *DistanceParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistanceParams.Marshal(b, m, deterministic)
}
func (m *DistanceParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistanceParams.Merge(m, src)
}
func (m *DistanceParams) XXX_Size() int {
	return xxx_messageInfo_DistanceParams.Size(m)
}
func (m *DistanceParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DistanceParams.DiscardUnknown(m)
}

var xxx_messageInfo_DistanceParams proto.InternalMessageInfo

func (m *DistanceParams) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *DistanceParams) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type Quote struct {
	Id          string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Phonenumber string          `protobuf:"bytes,3,opt,name=phonenumber,proto3" json:"phonenumber,omitempty"`
	Timestamp   int64           `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Email       string          `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Supplierids []*Suppliers    `protobuf:"bytes,6,rep,name=supplierids,proto3" json:"supplierids,omitempty"`
	Products    []*QuoteProduct `protobuf:"bytes,7,rep,name=products,proto3" json:"products,omitempty"`
	Name        string          `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	City        string          `protobuf:"bytes,11,opt,name=city,proto3" json:"city,omitempty"`
	Address     string          `protobuf:"bytes,12,opt,name=address,proto3" json:"address,omitempty"`
	Zip         string          `protobuf:"bytes,13,opt,name=zip,proto3" json:"zip,omitempty"`
	Size        string          `protobuf:"bytes,14,opt,name=size,proto3" json:"size,omitempty"`
	Userid      string          `protobuf:"bytes,15,opt,name=userid,proto3" json:"userid,omitempty"`
	Status      Status          `protobuf:"varint,16,opt,name=status,proto3,enum=quotes.Status" json:"status,omitempty"`
	SumPrice    float32         `protobuf:"fixed32,17,opt,name=sumPrice,proto3" json:"sumPrice,omitempty"`
	PaidPrice   float32         `protobuf:"fixed32,18,opt,name=paidPrice,proto3" json:"paidPrice,omitempty"`
	// uint32 quoteDate = 2;
	Services             []*ServiceInQuote `protobuf:"bytes,19,rep,name=services,proto3" json:"services,omitempty"`
	Qrcodeurl            string            `protobuf:"bytes,20,opt,name=qrcodeurl,proto3" json:"qrcodeurl,omitempty"`
	Delivery             float32           `protobuf:"fixed32,21,opt,name=delivery,proto3" json:"delivery,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Quote) Reset()         { *m = Quote{} }
func (m *Quote) String() string { return proto.CompactTextString(m) }
func (*Quote) ProtoMessage()    {}
func (*Quote) Descriptor() ([]byte, []int) {
	return fileDescriptor_15679ebe12a64146, []int{10}
}

func (m *Quote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quote.Unmarshal(m, b)
}
func (m *Quote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quote.Marshal(b, m, deterministic)
}
func (m *Quote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quote.Merge(m, src)
}
func (m *Quote) XXX_Size() int {
	return xxx_messageInfo_Quote.Size(m)
}
func (m *Quote) XXX_DiscardUnknown() {
	xxx_messageInfo_Quote.DiscardUnknown(m)
}

var xxx_messageInfo_Quote proto.InternalMessageInfo

func (m *Quote) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Quote) GetPhonenumber() string {
	if m != nil {
		return m.Phonenumber
	}
	return ""
}

func (m *Quote) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Quote) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Quote) GetSupplierids() []*Suppliers {
	if m != nil {
		return m.Supplierids
	}
	return nil
}

func (m *Quote) GetProducts() []*QuoteProduct {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *Quote) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Quote) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Quote) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Quote) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *Quote) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *Quote) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func (m *Quote) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_NEW
}

func (m *Quote) GetSumPrice() float32 {
	if m != nil {
		return m.SumPrice
	}
	return 0
}

func (m *Quote) GetPaidPrice() float32 {
	if m != nil {
		return m.PaidPrice
	}
	return 0
}

func (m *Quote) GetServices() []*ServiceInQuote {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *Quote) GetQrcodeurl() string {
	if m != nil {
		return m.Qrcodeurl
	}
	return ""
}

func (m *Quote) GetDelivery() float32 {
	if m != nil {
		return m.Delivery
	}
	return 0
}

func init() {
	proto.RegisterEnum("quotes.Status", Status_name, Status_value)
	proto.RegisterType((*QuoteResponse)(nil), "quotes.QuoteResponse")
	proto.RegisterType((*QuoteParams)(nil), "quotes.QuoteParams")
	proto.RegisterType((*Response)(nil), "quotes.Response")
	proto.RegisterType((*StatusParams)(nil), "quotes.StatusParams")
	proto.RegisterType((*Stats)(nil), "quotes.Stats")
	proto.RegisterType((*QuoteProduct)(nil), "quotes.QuoteProduct")
	proto.RegisterType((*ServiceInQuote)(nil), "quotes.ServiceInQuote")
	proto.RegisterType((*Suppliers)(nil), "quotes.Suppliers")
	proto.RegisterType((*Distance)(nil), "quotes.Distance")
	proto.RegisterType((*DistanceParams)(nil), "quotes.DistanceParams")
	proto.RegisterType((*Quote)(nil), "quotes.Quote")
}

func init() { proto.RegisterFile("quotes/quotes.proto", fileDescriptor_15679ebe12a64146) }

var fileDescriptor_15679ebe12a64146 = []byte{
	// 974 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x6d, 0x6f, 0xe3, 0x44,
	0x10, 0x26, 0x49, 0xf3, 0xe2, 0x49, 0x93, 0xba, 0xdb, 0xf4, 0xce, 0x8a, 0x10, 0xaa, 0x2c, 0x71,
	0xaa, 0x38, 0xd4, 0x42, 0x7a, 0x3a, 0xbe, 0x21, 0x95, 0xd8, 0xaa, 0x82, 0x42, 0x9a, 0xdb, 0xf4,
	0xe0, 0x23, 0xf2, 0xc5, 0x4b, 0xb3, 0x28, 0xb1, 0x5d, 0xef, 0xa6, 0x55, 0xee, 0x9f, 0xf0, 0x1d,
	0xfe, 0x00, 0x12, 0xff, 0x0f, 0xed, 0xec, 0x4b, 0x92, 0xbb, 0x43, 0xe2, 0x93, 0xe7, 0x79, 0x66,
	0x66, 0x67, 0x76, 0xf6, 0xd9, 0x35, 0x9c, 0x3c, 0xac, 0x73, 0xc9, 0xc4, 0xa5, 0xfe, 0x5c, 0x14,
	0x65, 0x2e, 0x73, 0xd2, 0xd0, 0xa8, 0xff, 0xbc, 0x28, 0xf3, 0x74, 0x3d, 0x97, 0xe2, 0xd2, 0x1a,
	0x3a, 0xa0, 0xff, 0x5c, 0xb0, 0xf2, 0x91, 0xcf, 0x99, 0xb8, 0xb4, 0x86, 0x76, 0x84, 0xaf, 0xa1,
	0xf3, 0x46, 0xe5, 0x52, 0x26, 0x8a, 0x3c, 0x13, 0x8c, 0x7c, 0x09, 0x66, 0xb1, 0xa0, 0x72, 0x56,
	0x3b, 0x6f, 0x0f, 0x3a, 0x17, 0xa6, 0x92, 0x0e, 0x33, 0xce, 0xf0, 0x12, 0xda, 0x48, 0x4c, 0x93,
	0x32, 0x59, 0x09, 0xd2, 0x85, 0xea, 0x28, 0x0a, 0x2a, 0x67, 0x95, 0x73, 0x8f, 0x56, 0x47, 0x11,
	0xf1, 0xa1, 0xf6, 0xfb, 0x93, 0x0c, 0xaa, 0x48, 0x28, 0x33, 0xec, 0x43, 0xcb, 0xd5, 0xe8, 0x42,
	0x95, 0xa7, 0x36, 0x9a, 0xa7, 0xe1, 0x6b, 0x38, 0x9c, 0xc9, 0x44, 0xae, 0x85, 0x59, 0xed, 0x19,
	0x34, 0x04, 0x62, 0x8c, 0xa9, 0x53, 0x83, 0x4c, 0x5e, 0xd5, 0xe5, 0xfd, 0x51, 0x85, 0xba, 0x4a,
	0xc4, 0x8c, 0x64, 0x2e, 0xf9, 0x23, 0xc3, 0x8c, 0x0e, 0x35, 0x88, 0x04, 0xd0, 0x2c, 0x58, 0x96,
	0xf2, 0xec, 0x1e, 0xd3, 0x3a, 0xd4, 0x42, 0x95, 0x91, 0xb2, 0x8c, 0xb3, 0x34, 0xa8, 0xe9, 0x0c,
	0x8d, 0x54, 0xe7, 0x19, 0x7b, 0x0a, 0x0e, 0x90, 0x54, 0xa6, 0x5a, 0x23, 0x29, 0x8a, 0xa5, 0x0a,
	0xad, 0xeb, 0x35, 0x0c, 0x24, 0x67, 0xd0, 0x2e, 0x4a, 0x56, 0x24, 0x65, 0x22, 0x79, 0x9e, 0x05,
	0x0d, 0xf4, 0xee, 0x52, 0xe4, 0x0b, 0x00, 0x73, 0x12, 0x2a, 0xa0, 0x89, 0x01, 0x3b, 0x0c, 0xf9,
	0x1c, 0xbc, 0x94, 0x2d, 0xf9, 0x23, 0x2b, 0x59, 0x1a, 0x00, 0xba, 0xb7, 0x84, 0xf2, 0xce, 0xf3,
	0x55, 0xb1, 0x64, 0x92, 0xa5, 0xc1, 0xa1, 0xf6, 0x3a, 0x02, 0xbd, 0x49, 0x36, 0x67, 0xcb, 0x25,
	0x4b, 0x83, 0x8e, 0xf1, 0x5a, 0x22, 0xfc, 0xab, 0x02, 0x87, 0xfa, 0x84, 0x74, 0x35, 0xf2, 0x12,
	0x9a, 0xa6, 0x30, 0xce, 0xa8, 0x3d, 0x38, 0xbe, 0x70, 0x22, 0x31, 0x31, 0xd4, 0x46, 0xa8, 0x29,
	0x3c, 0xc8, 0x8d, 0x99, 0x99, 0x32, 0x49, 0x0f, 0xea, 0x82, 0xbf, 0x67, 0x4b, 0x1c, 0x57, 0x95,
	0x6a, 0x60, 0x59, 0x3d, 0x2f, 0xc3, 0x3e, 0x59, 0x76, 0x81, 0xf3, 0x32, 0xec, 0xc2, 0xb2, 0x25,
	0xce, 0xc9, 0xb0, 0x65, 0x78, 0x0b, 0xdd, 0x99, 0x96, 0xe4, 0x28, 0xc3, 0x7e, 0x55, 0xa3, 0x46,
	0xa4, 0xae, 0x51, 0x27, 0x5a, 0x13, 0x4a, 0x6d, 0xc4, 0xc7, 0x8d, 0x86, 0xdf, 0x82, 0x37, 0x5b,
	0xe3, 0x01, 0x95, 0xe2, 0x43, 0xa5, 0xa9, 0x1e, 0x1e, 0x93, 0xa5, 0x11, 0x51, 0x8b, 0x6a, 0x10,
	0xbe, 0x80, 0x56, 0xc4, 0x85, 0x54, 0xb3, 0x23, 0x7d, 0x68, 0xa5, 0xc6, 0x36, 0xea, 0x73, 0x38,
	0x7c, 0x05, 0x5d, 0x1b, 0x67, 0x94, 0x4a, 0xe0, 0xe0, 0xb7, 0x32, 0x5f, 0x99, 0x0a, 0x68, 0xab,
	0x9a, 0x32, 0xb7, 0x2a, 0x95, 0x79, 0xf8, 0xe7, 0x01, 0xd4, 0xf5, 0xce, 0x3e, 0xec, 0x46, 0xe9,
	0x67, 0x91, 0x67, 0x2c, 0x5b, 0xaf, 0xde, 0xb1, 0x12, 0x27, 0xeb, 0xd1, 0x5d, 0x4a, 0x9d, 0xb1,
	0xe4, 0x2b, 0x26, 0x64, 0xb2, 0x2a, 0x70, 0xc6, 0x35, 0xba, 0x25, 0xd4, 0x6e, 0xd8, 0x2a, 0xe1,
	0x4b, 0x9c, 0xb3, 0x47, 0x35, 0x20, 0x57, 0xd0, 0x16, 0x66, 0x00, 0x3c, 0x15, 0x41, 0x03, 0xaf,
	0xf1, 0xb1, 0xbd, 0xc6, 0x6e, 0x36, 0x74, 0x37, 0x8a, 0x7c, 0x03, 0x2d, 0xab, 0x86, 0xa0, 0x89,
	0x19, 0xbd, 0xbd, 0x8b, 0x6f, 0x15, 0xe2, 0xa2, 0xd4, 0xd6, 0xb3, 0x64, 0xc5, 0x50, 0xb5, 0x1e,
	0x45, 0x5b, 0x71, 0x73, 0x2e, 0x37, 0x41, 0x5b, 0x73, 0xca, 0xc6, 0xeb, 0x93, 0xa6, 0x25, 0x13,
	0x02, 0x25, 0xec, 0x51, 0x0b, 0xd5, 0xd9, 0xbd, 0xe7, 0x05, 0x4a, 0xd7, 0xa3, 0xca, 0x54, 0xf9,
	0x4a, 0x15, 0x41, 0x57, 0xe7, 0x2b, 0x5b, 0x5d, 0xd4, 0xb5, 0x50, 0x4d, 0x06, 0x47, 0xc8, 0x1a,
	0x44, 0x5e, 0xb8, 0x47, 0xc2, 0x3f, 0xab, 0x9c, 0x77, 0x07, 0x5d, 0xb7, 0x43, 0x64, 0xdd, 0xa3,
	0xd1, 0x87, 0x96, 0x58, 0xaf, 0xa6, 0xa5, 0xd2, 0xd3, 0x31, 0x2a, 0xcf, 0x61, 0x35, 0xde, 0x22,
	0xe1, 0xa9, 0x76, 0x12, 0x74, 0x6e, 0x09, 0x32, 0x80, 0x96, 0x15, 0x5e, 0x70, 0x82, 0x33, 0x79,
	0xe6, 0x6a, 0xec, 0x49, 0x96, 0xba, 0x38, 0xb5, 0xe2, 0x43, 0x39, 0xcf, 0x53, 0xb6, 0x2e, 0x97,
	0x41, 0x0f, 0x1b, 0xde, 0x12, 0x28, 0x2e, 0x7d, 0xbb, 0x37, 0xc1, 0xa9, 0xee, 0xc5, 0xe2, 0xaf,
	0xfe, 0xa9, 0x40, 0x43, 0xb7, 0x4e, 0x9a, 0x50, 0x9b, 0xc4, 0xbf, 0xf8, 0x9f, 0x91, 0x1e, 0xf8,
	0xb3, 0xb7, 0xd3, 0xe9, 0x78, 0x14, 0xd3, 0x5f, 0xaf, 0xf1, 0x1b, 0xf9, 0x15, 0x42, 0xa0, 0x3b,
	0x1c, 0x8f, 0xe2, 0xc9, 0x9d, 0xe3, 0xaa, 0xe4, 0x08, 0xda, 0x53, 0x1a, 0x4f, 0xaf, 0xe9, 0xf5,
	0xdd, 0xe8, 0x76, 0xe2, 0xd7, 0x48, 0x17, 0x60, 0x4a, 0x6f, 0xa3, 0xb7, 0x43, 0xc4, 0x07, 0xa4,
	0x03, 0x5e, 0x14, 0x8f, 0x47, 0x3f, 0xc7, 0x34, 0x8e, 0xfc, 0xba, 0x82, 0xc3, 0xdb, 0x9f, 0xa6,
	0xe3, 0xf8, 0x2e, 0x8e, 0xfc, 0x06, 0xc2, 0xeb, 0xc9, 0x30, 0x1e, 0x8f, 0xe3, 0xc8, 0x6f, 0x92,
	0x53, 0x38, 0x76, 0x75, 0x69, 0xfc, 0x63, 0x3c, 0x54, 0x51, 0x2d, 0x72, 0x02, 0x47, 0xa6, 0xb0,
	0x23, 0xbd, 0xc1, 0xdf, 0x35, 0xf3, 0xd0, 0x98, 0x99, 0x90, 0x97, 0xd0, 0x9a, 0xb0, 0x27, 0xad,
	0xf8, 0xfd, 0xbf, 0x47, 0xdf, 0xb7, 0xd0, 0xfd, 0x0a, 0xae, 0xc0, 0xbb, 0x61, 0x12, 0xbd, 0x82,
	0x1c, 0x6d, 0x5f, 0xa4, 0x37, 0x6b, 0x56, 0x6e, 0xfa, 0xa7, 0xfb, 0x3f, 0x1f, 0x9b, 0x34, 0x80,
	0x43, 0x9b, 0xf4, 0xc3, 0x66, 0x14, 0x91, 0x93, 0x7d, 0xa9, 0xe2, 0xd5, 0xec, 0xef, 0x97, 0x26,
	0xaf, 0xa0, 0x1d, 0x31, 0xf5, 0x70, 0x6a, 0xf8, 0xc9, 0x94, 0x8f, 0xdb, 0xfb, 0x1a, 0xbc, 0x38,
	0xe5, 0xf2, 0x7f, 0x6e, 0xe6, 0x7b, 0xe8, 0x0d, 0x17, 0x49, 0x76, 0xcf, 0x66, 0x0b, 0x5e, 0x14,
	0x3c, 0xbb, 0x37, 0xe7, 0xd9, 0xdb, 0x97, 0xe6, 0x7f, 0x56, 0xbb, 0x84, 0xce, 0x0d, 0x93, 0x2a,
	0x88, 0x0b, 0xc9, 0xe7, 0x9f, 0x18, 0x48, 0x67, 0x77, 0x25, 0x41, 0xbe, 0x83, 0xf6, 0x0d, 0x93,
	0xee, 0xed, 0x72, 0xf2, 0xdc, 0x7f, 0xa5, 0xb6, 0x95, 0x2c, 0xff, 0xae, 0x81, 0x7f, 0xff, 0xab,
	0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x50, 0x17, 0x25, 0x1f, 0x4e, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QuoteServiceClient is the client API for QuoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QuoteServiceClient interface {
	NewQuote(ctx context.Context, in *Quote, opts ...grpc.CallOption) (*Response, error)
	GetQuotes(ctx context.Context, in *products.Query, opts ...grpc.CallOption) (*QuoteResponse, error)
	GetQuoteByID(ctx context.Context, in *QuoteParams, opts ...grpc.CallOption) (*Quote, error)
	DeleteQuote(ctx context.Context, in *QuoteParams, opts ...grpc.CallOption) (*Response, error)
	EditQuote(ctx context.Context, in *Quote, opts ...grpc.CallOption) (*Response, error)
	ChangeShippingStatus(ctx context.Context, in *StatusParams, opts ...grpc.CallOption) (*Response, error)
	GetStatistics(ctx context.Context, in *products.Query, opts ...grpc.CallOption) (*Stats, error)
	GetDistance(ctx context.Context, in *DistanceParams, opts ...grpc.CallOption) (*Distance, error)
}

type quoteServiceClient struct {
	cc *grpc.ClientConn
}

func NewQuoteServiceClient(cc *grpc.ClientConn) QuoteServiceClient {
	return &quoteServiceClient{cc}
}

func (c *quoteServiceClient) NewQuote(ctx context.Context, in *Quote, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/quotes.QuoteService/NewQuote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) GetQuotes(ctx context.Context, in *products.Query, opts ...grpc.CallOption) (*QuoteResponse, error) {
	out := new(QuoteResponse)
	err := c.cc.Invoke(ctx, "/quotes.QuoteService/GetQuotes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) GetQuoteByID(ctx context.Context, in *QuoteParams, opts ...grpc.CallOption) (*Quote, error) {
	out := new(Quote)
	err := c.cc.Invoke(ctx, "/quotes.QuoteService/GetQuoteByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) DeleteQuote(ctx context.Context, in *QuoteParams, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/quotes.QuoteService/DeleteQuote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) EditQuote(ctx context.Context, in *Quote, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/quotes.QuoteService/EditQuote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) ChangeShippingStatus(ctx context.Context, in *StatusParams, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/quotes.QuoteService/ChangeShippingStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) GetStatistics(ctx context.Context, in *products.Query, opts ...grpc.CallOption) (*Stats, error) {
	out := new(Stats)
	err := c.cc.Invoke(ctx, "/quotes.QuoteService/GetStatistics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) GetDistance(ctx context.Context, in *DistanceParams, opts ...grpc.CallOption) (*Distance, error) {
	out := new(Distance)
	err := c.cc.Invoke(ctx, "/quotes.QuoteService/GetDistance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuoteServiceServer is the server API for QuoteService service.
type QuoteServiceServer interface {
	NewQuote(context.Context, *Quote) (*Response, error)
	GetQuotes(context.Context, *products.Query) (*QuoteResponse, error)
	GetQuoteByID(context.Context, *QuoteParams) (*Quote, error)
	DeleteQuote(context.Context, *QuoteParams) (*Response, error)
	EditQuote(context.Context, *Quote) (*Response, error)
	ChangeShippingStatus(context.Context, *StatusParams) (*Response, error)
	GetStatistics(context.Context, *products.Query) (*Stats, error)
	GetDistance(context.Context, *DistanceParams) (*Distance, error)
}

// UnimplementedQuoteServiceServer can be embedded to have forward compatible implementations.
type UnimplementedQuoteServiceServer struct {
}

func (*UnimplementedQuoteServiceServer) NewQuote(ctx context.Context, req *Quote) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewQuote not implemented")
}
func (*UnimplementedQuoteServiceServer) GetQuotes(ctx context.Context, req *products.Query) (*QuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuotes not implemented")
}
func (*UnimplementedQuoteServiceServer) GetQuoteByID(ctx context.Context, req *QuoteParams) (*Quote, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuoteByID not implemented")
}
func (*UnimplementedQuoteServiceServer) DeleteQuote(ctx context.Context, req *QuoteParams) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteQuote not implemented")
}
func (*UnimplementedQuoteServiceServer) EditQuote(ctx context.Context, req *Quote) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditQuote not implemented")
}
func (*UnimplementedQuoteServiceServer) ChangeShippingStatus(ctx context.Context, req *StatusParams) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeShippingStatus not implemented")
}
func (*UnimplementedQuoteServiceServer) GetStatistics(ctx context.Context, req *products.Query) (*Stats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatistics not implemented")
}
func (*UnimplementedQuoteServiceServer) GetDistance(ctx context.Context, req *DistanceParams) (*Distance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDistance not implemented")
}

func RegisterQuoteServiceServer(s *grpc.Server, srv QuoteServiceServer) {
	s.RegisterService(&_QuoteService_serviceDesc, srv)
}

func _QuoteService_NewQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Quote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).NewQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quotes.QuoteService/NewQuote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).NewQuote(ctx, req.(*Quote))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_GetQuotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(products.Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).GetQuotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quotes.QuoteService/GetQuotes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).GetQuotes(ctx, req.(*products.Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_GetQuoteByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).GetQuoteByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quotes.QuoteService/GetQuoteByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).GetQuoteByID(ctx, req.(*QuoteParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_DeleteQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).DeleteQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quotes.QuoteService/DeleteQuote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).DeleteQuote(ctx, req.(*QuoteParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_EditQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Quote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).EditQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quotes.QuoteService/EditQuote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).EditQuote(ctx, req.(*Quote))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_ChangeShippingStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).ChangeShippingStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quotes.QuoteService/ChangeShippingStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).ChangeShippingStatus(ctx, req.(*StatusParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_GetStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(products.Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).GetStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quotes.QuoteService/GetStatistics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).GetStatistics(ctx, req.(*products.Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_GetDistance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DistanceParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).GetDistance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quotes.QuoteService/GetDistance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).GetDistance(ctx, req.(*DistanceParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _QuoteService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "quotes.QuoteService",
	HandlerType: (*QuoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewQuote",
			Handler:    _QuoteService_NewQuote_Handler,
		},
		{
			MethodName: "GetQuotes",
			Handler:    _QuoteService_GetQuotes_Handler,
		},
		{
			MethodName: "GetQuoteByID",
			Handler:    _QuoteService_GetQuoteByID_Handler,
		},
		{
			MethodName: "DeleteQuote",
			Handler:    _QuoteService_DeleteQuote_Handler,
		},
		{
			MethodName: "EditQuote",
			Handler:    _QuoteService_EditQuote_Handler,
		},
		{
			MethodName: "ChangeShippingStatus",
			Handler:    _QuoteService_ChangeShippingStatus_Handler,
		},
		{
			MethodName: "GetStatistics",
			Handler:    _QuoteService_GetStatistics_Handler,
		},
		{
			MethodName: "GetDistance",
			Handler:    _QuoteService_GetDistance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "quotes/quotes.proto",
}
