// Code generated by protoc-gen-go. DO NOT EDIT.
// source: landing/landing.proto

package landing

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Teams struct {
	Teams                []*Team  `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Teams) Reset()         { *m = Teams{} }
func (m *Teams) String() string { return proto.CompactTextString(m) }
func (*Teams) ProtoMessage()    {}
func (*Teams) Descriptor() ([]byte, []int) {
	return fileDescriptor_352e6f3f8b358066, []int{0}
}

func (m *Teams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Teams.Unmarshal(m, b)
}
func (m *Teams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Teams.Marshal(b, m, deterministic)
}
func (m *Teams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Teams.Merge(m, src)
}
func (m *Teams) XXX_Size() int {
	return xxx_messageInfo_Teams.Size(m)
}
func (m *Teams) XXX_DiscardUnknown() {
	xxx_messageInfo_Teams.DiscardUnknown(m)
}

var xxx_messageInfo_Teams proto.InternalMessageInfo

func (m *Teams) GetTeams() []*Team {
	if m != nil {
		return m.Teams
	}
	return nil
}

type Team struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rating               float32  `protobuf:"fixed32,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Image                string   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Timestamp            int64    `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Team) Reset()         { *m = Team{} }
func (m *Team) String() string { return proto.CompactTextString(m) }
func (*Team) ProtoMessage()    {}
func (*Team) Descriptor() ([]byte, []int) {
	return fileDescriptor_352e6f3f8b358066, []int{1}
}

func (m *Team) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Team.Unmarshal(m, b)
}
func (m *Team) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Team.Marshal(b, m, deterministic)
}
func (m *Team) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Team.Merge(m, src)
}
func (m *Team) XXX_Size() int {
	return xxx_messageInfo_Team.Size(m)
}
func (m *Team) XXX_DiscardUnknown() {
	xxx_messageInfo_Team.DiscardUnknown(m)
}

var xxx_messageInfo_Team proto.InternalMessageInfo

func (m *Team) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Team) GetRating() float32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *Team) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Team) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Team) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Portfolio struct {
	Details              string   `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	Sector               string   `protobuf:"bytes,2,opt,name=sector,proto3" json:"sector,omitempty"`
	Image                string   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id                   string   `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Portfolio) Reset()         { *m = Portfolio{} }
func (m *Portfolio) String() string { return proto.CompactTextString(m) }
func (*Portfolio) ProtoMessage()    {}
func (*Portfolio) Descriptor() ([]byte, []int) {
	return fileDescriptor_352e6f3f8b358066, []int{2}
}

func (m *Portfolio) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Portfolio.Unmarshal(m, b)
}
func (m *Portfolio) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Portfolio.Marshal(b, m, deterministic)
}
func (m *Portfolio) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Portfolio.Merge(m, src)
}
func (m *Portfolio) XXX_Size() int {
	return xxx_messageInfo_Portfolio.Size(m)
}
func (m *Portfolio) XXX_DiscardUnknown() {
	xxx_messageInfo_Portfolio.DiscardUnknown(m)
}

var xxx_messageInfo_Portfolio proto.InternalMessageInfo

func (m *Portfolio) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *Portfolio) GetSector() string {
	if m != nil {
		return m.Sector
	}
	return ""
}

func (m *Portfolio) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Portfolio) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Portfolio) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Portfolios struct {
	Portfolios           []*Portfolio `protobuf:"bytes,1,rep,name=portfolios,proto3" json:"portfolios,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Portfolios) Reset()         { *m = Portfolios{} }
func (m *Portfolios) String() string { return proto.CompactTextString(m) }
func (*Portfolios) ProtoMessage()    {}
func (*Portfolios) Descriptor() ([]byte, []int) {
	return fileDescriptor_352e6f3f8b358066, []int{3}
}

func (m *Portfolios) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Portfolios.Unmarshal(m, b)
}
func (m *Portfolios) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Portfolios.Marshal(b, m, deterministic)
}
func (m *Portfolios) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Portfolios.Merge(m, src)
}
func (m *Portfolios) XXX_Size() int {
	return xxx_messageInfo_Portfolios.Size(m)
}
func (m *Portfolios) XXX_DiscardUnknown() {
	xxx_messageInfo_Portfolios.DiscardUnknown(m)
}

var xxx_messageInfo_Portfolios proto.InternalMessageInfo

func (m *Portfolios) GetPortfolios() []*Portfolio {
	if m != nil {
		return m.Portfolios
	}
	return nil
}

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_352e6f3f8b358066, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type Params struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_352e6f3f8b358066, []int{5}
}

func (m *Params) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Params.Unmarshal(m, b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Params.Marshal(b, m, deterministic)
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return xxx_messageInfo_Params.Size(m)
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Params) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Teams)(nil), "Teams")
	proto.RegisterType((*Team)(nil), "Team")
	proto.RegisterType((*Portfolio)(nil), "Portfolio")
	proto.RegisterType((*Portfolios)(nil), "Portfolios")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*Params)(nil), "Params")
}

func init() { proto.RegisterFile("landing/landing.proto", fileDescriptor_352e6f3f8b358066) }

var fileDescriptor_352e6f3f8b358066 = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x25, 0x5d, 0xdb, 0xad, 0x77, 0x3a, 0x21, 0xa8, 0x94, 0xcd, 0x87, 0x52, 0x1c, 0x14, 0x91,
	0x0a, 0xf3, 0xc5, 0x0f, 0x10, 0xf6, 0x22, 0x63, 0x44, 0x7f, 0x20, 0xae, 0xd7, 0x11, 0x68, 0x9b,
	0xd2, 0x04, 0xf7, 0xec, 0x9b, 0xbf, 0xe9, 0x9f, 0x48, 0x93, 0xae, 0xeb, 0x64, 0x3e, 0x35, 0xe7,
	0xdc, 0x9b, 0x7b, 0x4e, 0xcf, 0x0d, 0x5c, 0xe5, 0xbc, 0xcc, 0x44, 0xb9, 0x7d, 0x68, 0xbf, 0x69,
	0x55, 0x4b, 0x2d, 0xe3, 0x5b, 0xf0, 0xde, 0x90, 0x17, 0x8a, 0xce, 0xc0, 0xd3, 0xcd, 0x21, 0x24,
	0xd1, 0x20, 0x19, 0x2f, 0xbc, 0xb4, 0xa1, 0x99, 0xe5, 0xe2, 0x6f, 0x02, 0x6e, 0x83, 0x29, 0x05,
	0xb7, 0xe4, 0x05, 0x86, 0x24, 0x22, 0x49, 0xc0, 0xcc, 0x99, 0x5e, 0x83, 0x5f, 0x73, 0x2d, 0xca,
	0x6d, 0xe8, 0x44, 0x24, 0x71, 0x58, 0x8b, 0xe8, 0x25, 0x78, 0xa2, 0xe0, 0x5b, 0x0c, 0x07, 0xa6,
	0xd9, 0x02, 0x1a, 0xc1, 0x38, 0x43, 0xb5, 0xa9, 0x45, 0xa5, 0x85, 0x2c, 0x43, 0xd7, 0xd4, 0xfa,
	0x14, 0xbd, 0x81, 0x40, 0x8b, 0x02, 0x95, 0xe6, 0x45, 0x15, 0x7a, 0x11, 0x49, 0x06, 0xec, 0x40,
	0xc4, 0x5f, 0x04, 0x82, 0xb5, 0xac, 0xf5, 0x87, 0xcc, 0x85, 0xa4, 0x21, 0x0c, 0x33, 0xd4, 0x5c,
	0xe4, 0xaa, 0xb5, 0xb4, 0x87, 0x8d, 0x2b, 0x85, 0x1b, 0x2d, 0x6b, 0xe3, 0x2a, 0x60, 0x2d, 0xfa,
	0xc7, 0xd5, 0x91, 0xa6, 0xfb, 0x47, 0x93, 0x4e, 0xc0, 0x11, 0x99, 0xb1, 0x12, 0x30, 0x47, 0x64,
	0xf1, 0x13, 0x40, 0x67, 0x41, 0xd1, 0x3b, 0x80, 0xaa, 0x43, 0x6d, 0x7c, 0x90, 0x76, 0x0d, 0xac,
	0x57, 0x8d, 0x01, 0x46, 0x0c, 0x55, 0x25, 0x4b, 0x85, 0xf1, 0x3d, 0xf8, 0x6b, 0x5e, 0x37, 0xd9,
	0x9f, 0x4a, 0xd5, 0x6a, 0x3a, 0x7b, 0xcd, 0xc5, 0x0f, 0x81, 0xc9, 0x8b, 0x5d, 0xdd, 0x2b, 0xd6,
	0x9f, 0x62, 0x83, 0x74, 0x06, 0xc3, 0x15, 0xee, 0xcc, 0x5e, 0xec, 0xba, 0xa6, 0x41, 0xba, 0x9f,
	0x4e, 0x67, 0x30, 0x5a, 0xa2, 0xb6, 0xbb, 0x1d, 0xa6, 0x56, 0x68, 0xea, 0xa7, 0x96, 0x88, 0x00,
	0x9e, 0x31, 0x47, 0x8d, 0xe6, 0x72, 0x57, 0xee, 0x5d, 0x9f, 0xc3, 0xd9, 0x0a, 0x77, 0x87, 0xa0,
	0x7b, 0x3f, 0x74, 0xdc, 0x76, 0xbe, 0x44, 0xdd, 0x0b, 0xa3, 0x9b, 0x35, 0x4e, 0x7b, 0xec, 0x1c,
	0x2e, 0xac, 0xde, 0x61, 0xe0, 0x09, 0xd1, 0x77, 0xdf, 0xbc, 0xc9, 0xc7, 0xdf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xb8, 0x87, 0xbe, 0xe9, 0xac, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LandingServiceClient is the client API for LandingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LandingServiceClient interface {
	NewTeam(ctx context.Context, in *Team, opts ...grpc.CallOption) (*Response, error)
	GetTeams(ctx context.Context, in *Params, opts ...grpc.CallOption) (*Teams, error)
	DeleteTeam(ctx context.Context, in *Params, opts ...grpc.CallOption) (*Response, error)
	NewPortfolio(ctx context.Context, in *Portfolio, opts ...grpc.CallOption) (*Response, error)
	GetPortfolios(ctx context.Context, in *Params, opts ...grpc.CallOption) (*Portfolios, error)
	DeletePortfolio(ctx context.Context, in *Params, opts ...grpc.CallOption) (*Response, error)
}

type landingServiceClient struct {
	cc *grpc.ClientConn
}

func NewLandingServiceClient(cc *grpc.ClientConn) LandingServiceClient {
	return &landingServiceClient{cc}
}

func (c *landingServiceClient) NewTeam(ctx context.Context, in *Team, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/LandingService/NewTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *landingServiceClient) GetTeams(ctx context.Context, in *Params, opts ...grpc.CallOption) (*Teams, error) {
	out := new(Teams)
	err := c.cc.Invoke(ctx, "/LandingService/GetTeams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *landingServiceClient) DeleteTeam(ctx context.Context, in *Params, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/LandingService/DeleteTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *landingServiceClient) NewPortfolio(ctx context.Context, in *Portfolio, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/LandingService/NewPortfolio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *landingServiceClient) GetPortfolios(ctx context.Context, in *Params, opts ...grpc.CallOption) (*Portfolios, error) {
	out := new(Portfolios)
	err := c.cc.Invoke(ctx, "/LandingService/GetPortfolios", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *landingServiceClient) DeletePortfolio(ctx context.Context, in *Params, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/LandingService/DeletePortfolio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LandingServiceServer is the server API for LandingService service.
type LandingServiceServer interface {
	NewTeam(context.Context, *Team) (*Response, error)
	GetTeams(context.Context, *Params) (*Teams, error)
	DeleteTeam(context.Context, *Params) (*Response, error)
	NewPortfolio(context.Context, *Portfolio) (*Response, error)
	GetPortfolios(context.Context, *Params) (*Portfolios, error)
	DeletePortfolio(context.Context, *Params) (*Response, error)
}

// UnimplementedLandingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLandingServiceServer struct {
}

func (*UnimplementedLandingServiceServer) NewTeam(ctx context.Context, req *Team) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewTeam not implemented")
}
func (*UnimplementedLandingServiceServer) GetTeams(ctx context.Context, req *Params) (*Teams, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeams not implemented")
}
func (*UnimplementedLandingServiceServer) DeleteTeam(ctx context.Context, req *Params) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTeam not implemented")
}
func (*UnimplementedLandingServiceServer) NewPortfolio(ctx context.Context, req *Portfolio) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewPortfolio not implemented")
}
func (*UnimplementedLandingServiceServer) GetPortfolios(ctx context.Context, req *Params) (*Portfolios, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPortfolios not implemented")
}
func (*UnimplementedLandingServiceServer) DeletePortfolio(ctx context.Context, req *Params) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePortfolio not implemented")
}

func RegisterLandingServiceServer(s *grpc.Server, srv LandingServiceServer) {
	s.RegisterService(&_LandingService_serviceDesc, srv)
}

func _LandingService_NewTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Team)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LandingServiceServer).NewTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LandingService/NewTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LandingServiceServer).NewTeam(ctx, req.(*Team))
	}
	return interceptor(ctx, in, info, handler)
}

func _LandingService_GetTeams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Params)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LandingServiceServer).GetTeams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LandingService/GetTeams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LandingServiceServer).GetTeams(ctx, req.(*Params))
	}
	return interceptor(ctx, in, info, handler)
}

func _LandingService_DeleteTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Params)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LandingServiceServer).DeleteTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LandingService/DeleteTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LandingServiceServer).DeleteTeam(ctx, req.(*Params))
	}
	return interceptor(ctx, in, info, handler)
}

func _LandingService_NewPortfolio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Portfolio)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LandingServiceServer).NewPortfolio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LandingService/NewPortfolio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LandingServiceServer).NewPortfolio(ctx, req.(*Portfolio))
	}
	return interceptor(ctx, in, info, handler)
}

func _LandingService_GetPortfolios_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Params)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LandingServiceServer).GetPortfolios(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LandingService/GetPortfolios",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LandingServiceServer).GetPortfolios(ctx, req.(*Params))
	}
	return interceptor(ctx, in, info, handler)
}

func _LandingService_DeletePortfolio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Params)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LandingServiceServer).DeletePortfolio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LandingService/DeletePortfolio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LandingServiceServer).DeletePortfolio(ctx, req.(*Params))
	}
	return interceptor(ctx, in, info, handler)
}

var _LandingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "LandingService",
	HandlerType: (*LandingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewTeam",
			Handler:    _LandingService_NewTeam_Handler,
		},
		{
			MethodName: "GetTeams",
			Handler:    _LandingService_GetTeams_Handler,
		},
		{
			MethodName: "DeleteTeam",
			Handler:    _LandingService_DeleteTeam_Handler,
		},
		{
			MethodName: "NewPortfolio",
			Handler:    _LandingService_NewPortfolio_Handler,
		},
		{
			MethodName: "GetPortfolios",
			Handler:    _LandingService_GetPortfolios_Handler,
		},
		{
			MethodName: "DeletePortfolio",
			Handler:    _LandingService_DeletePortfolio_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "landing/landing.proto",
}
