// Code generated by protoc-gen-go. DO NOT EDIT.
// source: products/products.proto

package products

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProductParams struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Jwt                  string   `protobuf:"bytes,2,opt,name=jwt,proto3" json:"jwt,omitempty"`
	Query                *Query   `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductParams) Reset()         { *m = ProductParams{} }
func (m *ProductParams) String() string { return proto.CompactTextString(m) }
func (*ProductParams) ProtoMessage()    {}
func (*ProductParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8b65708d5d9f169, []int{0}
}

func (m *ProductParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductParams.Unmarshal(m, b)
}
func (m *ProductParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductParams.Marshal(b, m, deterministic)
}
func (m *ProductParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductParams.Merge(m, src)
}
func (m *ProductParams) XXX_Size() int {
	return xxx_messageInfo_ProductParams.Size(m)
}
func (m *ProductParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductParams.DiscardUnknown(m)
}

var xxx_messageInfo_ProductParams proto.InternalMessageInfo

func (m *ProductParams) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProductParams) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

func (m *ProductParams) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

type Query struct {
	Querystring          string   `protobuf:"bytes,1,opt,name=Querystring,proto3" json:"Querystring,omitempty"`
	SortFields           []string `protobuf:"bytes,2,rep,name=sortFields,proto3" json:"sortFields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8b65708d5d9f169, []int{1}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetQuerystring() string {
	if m != nil {
		return m.Querystring
	}
	return ""
}

func (m *Query) GetSortFields() []string {
	if m != nil {
		return m.SortFields
	}
	return nil
}

type ProductResponse struct {
	Products             []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProductResponse) Reset()         { *m = ProductResponse{} }
func (m *ProductResponse) String() string { return proto.CompactTextString(m) }
func (*ProductResponse) ProtoMessage()    {}
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8b65708d5d9f169, []int{2}
}

func (m *ProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductResponse.Unmarshal(m, b)
}
func (m *ProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductResponse.Marshal(b, m, deterministic)
}
func (m *ProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductResponse.Merge(m, src)
}
func (m *ProductResponse) XXX_Size() int {
	return xxx_messageInfo_ProductResponse.Size(m)
}
func (m *ProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProductResponse proto.InternalMessageInfo

func (m *ProductResponse) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8b65708d5d9f169, []int{3}
}

func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (m *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(m, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

type ImageResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageResponse) Reset()         { *m = ImageResponse{} }
func (m *ImageResponse) String() string { return proto.CompactTextString(m) }
func (*ImageResponse) ProtoMessage()    {}
func (*ImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8b65708d5d9f169, []int{4}
}

func (m *ImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageResponse.Unmarshal(m, b)
}
func (m *ImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageResponse.Marshal(b, m, deterministic)
}
func (m *ImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageResponse.Merge(m, src)
}
func (m *ImageResponse) XXX_Size() int {
	return xxx_messageInfo_ImageResponse.Size(m)
}
func (m *ImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ImageResponse proto.InternalMessageInfo

func (m *ImageResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Image struct {
	Image                string   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Ext                  string   `protobuf:"bytes,2,opt,name=ext,proto3" json:"ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8b65708d5d9f169, []int{5}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Image) GetExt() string {
	if m != nil {
		return m.Ext
	}
	return ""
}

type Product struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Qtyinstock           int32    `protobuf:"varint,2,opt,name=qtyinstock,proto3" json:"qtyinstock,omitempty"`
	Category             string   `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Subcategory          string   `protobuf:"bytes,4,opt,name=subcategory,proto3" json:"subcategory,omitempty"`
	Sector               string   `protobuf:"bytes,5,opt,name=sector,proto3" json:"sector,omitempty"`
	Buyingprice          float32  `protobuf:"fixed32,6,opt,name=buyingprice,proto3" json:"buyingprice,omitempty"`
	Desiredprofit        float32  `protobuf:"fixed32,7,opt,name=desiredprofit,proto3" json:"desiredprofit,omitempty"`
	Sellingprice         float32  `protobuf:"fixed32,8,opt,name=sellingprice,proto3" json:"sellingprice,omitempty"`
	Addedtime            int64    `protobuf:"varint,9,opt,name=addedtime,proto3" json:"addedtime,omitempty"`
	Description          string   `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	Id                   string   `protobuf:"bytes,11,opt,name=id,proto3" json:"id,omitempty"`
	Sizew                float32  `protobuf:"fixed32,12,opt,name=sizew,proto3" json:"sizew,omitempty"`
	Sizel                float32  `protobuf:"fixed32,13,opt,name=sizel,proto3" json:"sizel,omitempty"`
	Sized                float32  `protobuf:"fixed32,14,opt,name=sized,proto3" json:"sized,omitempty"`
	Sizeh                float32  `protobuf:"fixed32,15,opt,name=sizeh,proto3" json:"sizeh,omitempty"`
	Weight               float32  `protobuf:"fixed32,16,opt,name=weight,proto3" json:"weight,omitempty"`
	Userid               string   `protobuf:"bytes,17,opt,name=userid,proto3" json:"userid,omitempty"`
	Images               []string `protobuf:"bytes,18,rep,name=images,proto3" json:"images,omitempty"`
	Barcode              string   `protobuf:"bytes,19,opt,name=barcode,proto3" json:"barcode,omitempty"`
	Soldby               string   `protobuf:"bytes,20,opt,name=soldby,proto3" json:"soldby,omitempty"`
	Discount             float32  `protobuf:"fixed32,21,opt,name=discount,proto3" json:"discount,omitempty"`
	Brand                string   `protobuf:"bytes,22,opt,name=brand,proto3" json:"brand,omitempty"`
	Brandmodel           string   `protobuf:"bytes,23,opt,name=brandmodel,proto3" json:"brandmodel,omitempty"`
	Volume               float32  `protobuf:"fixed32,24,opt,name=volume,proto3" json:"volume,omitempty"`
	Measurementunit      string   `protobuf:"bytes,25,opt,name=measurementunit,proto3" json:"measurementunit,omitempty"`
	Measurementvalue     float32  `protobuf:"fixed32,26,opt,name=measurementvalue,proto3" json:"measurementvalue,omitempty"`
	Portionunit          string   `protobuf:"bytes,27,opt,name=portionunit,proto3" json:"portionunit,omitempty"`
	Portionvalue         float32  `protobuf:"fixed32,28,opt,name=portionvalue,proto3" json:"portionvalue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8b65708d5d9f169, []int{6}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetQtyinstock() int32 {
	if m != nil {
		return m.Qtyinstock
	}
	return 0
}

func (m *Product) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Product) GetSubcategory() string {
	if m != nil {
		return m.Subcategory
	}
	return ""
}

func (m *Product) GetSector() string {
	if m != nil {
		return m.Sector
	}
	return ""
}

func (m *Product) GetBuyingprice() float32 {
	if m != nil {
		return m.Buyingprice
	}
	return 0
}

func (m *Product) GetDesiredprofit() float32 {
	if m != nil {
		return m.Desiredprofit
	}
	return 0
}

func (m *Product) GetSellingprice() float32 {
	if m != nil {
		return m.Sellingprice
	}
	return 0
}

func (m *Product) GetAddedtime() int64 {
	if m != nil {
		return m.Addedtime
	}
	return 0
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetSizew() float32 {
	if m != nil {
		return m.Sizew
	}
	return 0
}

func (m *Product) GetSizel() float32 {
	if m != nil {
		return m.Sizel
	}
	return 0
}

func (m *Product) GetSized() float32 {
	if m != nil {
		return m.Sized
	}
	return 0
}

func (m *Product) GetSizeh() float32 {
	if m != nil {
		return m.Sizeh
	}
	return 0
}

func (m *Product) GetWeight() float32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Product) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func (m *Product) GetImages() []string {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *Product) GetBarcode() string {
	if m != nil {
		return m.Barcode
	}
	return ""
}

func (m *Product) GetSoldby() string {
	if m != nil {
		return m.Soldby
	}
	return ""
}

func (m *Product) GetDiscount() float32 {
	if m != nil {
		return m.Discount
	}
	return 0
}

func (m *Product) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *Product) GetBrandmodel() string {
	if m != nil {
		return m.Brandmodel
	}
	return ""
}

func (m *Product) GetVolume() float32 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *Product) GetMeasurementunit() string {
	if m != nil {
		return m.Measurementunit
	}
	return ""
}

func (m *Product) GetMeasurementvalue() float32 {
	if m != nil {
		return m.Measurementvalue
	}
	return 0
}

func (m *Product) GetPortionunit() string {
	if m != nil {
		return m.Portionunit
	}
	return ""
}

func (m *Product) GetPortionvalue() float32 {
	if m != nil {
		return m.Portionvalue
	}
	return 0
}

func init() {
	proto.RegisterType((*ProductParams)(nil), "products.ProductParams")
	proto.RegisterType((*Query)(nil), "products.Query")
	proto.RegisterType((*ProductResponse)(nil), "products.ProductResponse")
	proto.RegisterType((*EmptyResponse)(nil), "products.EmptyResponse")
	proto.RegisterType((*ImageResponse)(nil), "products.ImageResponse")
	proto.RegisterType((*Image)(nil), "products.Image")
	proto.RegisterType((*Product)(nil), "products.Product")
}

func init() { proto.RegisterFile("products/products.proto", fileDescriptor_a8b65708d5d9f169) }

var fileDescriptor_a8b65708d5d9f169 = []byte{
	// 696 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x95, 0xdf, 0x6f, 0xd3, 0x30,
	0x10, 0xc7, 0xd5, 0x76, 0xed, 0xd6, 0xeb, 0xfa, 0x63, 0x66, 0x6c, 0x5e, 0x99, 0x50, 0xa9, 0x40,
	0xaa, 0x90, 0xd8, 0xa4, 0xf2, 0x80, 0x90, 0x78, 0x00, 0xb4, 0x81, 0xf6, 0x82, 0x46, 0x10, 0x12,
	0xaf, 0x69, 0x7c, 0x74, 0x86, 0x24, 0xce, 0x6c, 0x67, 0x5d, 0x78, 0xe2, 0xbf, 0xe1, 0xdf, 0x44,
	0xb6, 0xf3, 0xab, 0x94, 0x21, 0xde, 0xee, 0xfb, 0xb1, 0xef, 0x7c, 0xf6, 0x5d, 0x2e, 0x70, 0x98,
	0x48, 0xc1, 0xd2, 0x40, 0xab, 0xd3, 0xc2, 0x38, 0x49, 0xa4, 0xd0, 0x82, 0xec, 0x14, 0x7a, 0xfa,
	0x05, 0xfa, 0x97, 0xce, 0xbe, 0xf4, 0xa5, 0x1f, 0x29, 0x32, 0x80, 0x26, 0x67, 0xb4, 0x31, 0x69,
	0xcc, 0xba, 0x5e, 0x93, 0x33, 0x32, 0x82, 0xd6, 0xb7, 0x95, 0xa6, 0x4d, 0x0b, 0x8c, 0x49, 0x9e,
	0x40, 0xfb, 0x3a, 0x45, 0x99, 0xd1, 0xad, 0x49, 0x63, 0xd6, 0x9b, 0x0f, 0x4f, 0xca, 0xe0, 0x1f,
	0x0d, 0xf6, 0xdc, 0xea, 0xf4, 0x02, 0xda, 0x56, 0x93, 0x09, 0xf4, 0xac, 0xa1, 0xb4, 0xe4, 0xf1,
	0x32, 0x0f, 0x5d, 0x47, 0xe4, 0x21, 0x80, 0x12, 0x52, 0xbf, 0xe3, 0x18, 0x32, 0x45, 0x9b, 0x93,
	0xd6, 0xac, 0xeb, 0xd5, 0xc8, 0xf4, 0x35, 0x0c, 0xf3, 0x24, 0x3d, 0x54, 0x89, 0x88, 0x15, 0x92,
	0x67, 0x50, 0xde, 0x81, 0x36, 0x26, 0xad, 0x59, 0x6f, 0xbe, 0x57, 0xe5, 0x51, 0x6c, 0xae, 0xae,
	0x39, 0x84, 0xfe, 0x79, 0x94, 0xe8, 0xac, 0xf0, 0x9f, 0x3e, 0x82, 0xfe, 0x45, 0xe4, 0x2f, 0xb1,
	0x0c, 0x38, 0x82, 0x56, 0x2a, 0xc3, 0x3c, 0x3b, 0x63, 0x4e, 0x4f, 0xa1, 0x6d, 0xb7, 0x90, 0x7d,
	0x68, 0x73, 0x63, 0xe4, 0x8b, 0x4e, 0x18, 0x07, 0xbc, 0x2d, 0x1f, 0x06, 0x6f, 0xf5, 0xf4, 0x57,
	0x07, 0xb6, 0xf3, 0xa3, 0x09, 0x81, 0xad, 0xd8, 0x8f, 0x0a, 0x17, 0x6b, 0x9b, 0x6b, 0x5e, 0xeb,
	0x8c, 0xc7, 0x4a, 0x8b, 0xe0, 0xbb, 0x75, 0x6c, 0x7b, 0x35, 0x42, 0xc6, 0xb0, 0x13, 0xf8, 0x1a,
	0x97, 0x42, 0x66, 0xb4, 0x65, 0xfd, 0x4a, 0x6d, 0x1e, 0x51, 0xa5, 0x8b, 0x72, 0x79, 0xcb, 0x3d,
	0x62, 0x0d, 0x91, 0x03, 0xe8, 0x28, 0x0c, 0xb4, 0x90, 0xb4, 0x6d, 0x17, 0x73, 0x65, 0x3c, 0x17,
	0x69, 0xc6, 0xe3, 0x65, 0x22, 0x79, 0x80, 0xb4, 0x33, 0x69, 0xcc, 0x9a, 0x5e, 0x1d, 0x91, 0xc7,
	0xd0, 0x67, 0xa8, 0xb8, 0x44, 0x96, 0x48, 0xf1, 0x95, 0x6b, 0xba, 0x6d, 0xf7, 0xac, 0x43, 0x32,
	0x85, 0x5d, 0x85, 0x61, 0x58, 0x06, 0xda, 0xb1, 0x9b, 0xd6, 0x18, 0x39, 0x86, 0xae, 0xcf, 0x18,
	0x32, 0xcd, 0x23, 0xa4, 0xdd, 0x49, 0x63, 0xd6, 0xf2, 0x2a, 0x60, 0x32, 0x61, 0xa8, 0x02, 0xc9,
	0x13, 0xcd, 0x45, 0x4c, 0xc1, 0xdd, 0xa1, 0x86, 0xf2, 0xe6, 0xeb, 0x95, 0xcd, 0xb7, 0x0f, 0x6d,
	0xc5, 0x7f, 0xe0, 0x8a, 0xee, 0xda, 0xc3, 0x9c, 0x28, 0x68, 0x48, 0xfb, 0x15, 0x0d, 0x0b, 0xca,
	0xe8, 0xa0, 0xa2, 0x65, 0x84, 0x2b, 0x3a, 0xac, 0xe8, 0x95, 0x79, 0xab, 0x15, 0xf2, 0xe5, 0x95,
	0xa6, 0x23, 0x8b, 0x73, 0x65, 0x78, 0xaa, 0x50, 0x72, 0x46, 0xf7, 0xdc, 0x1b, 0x3a, 0x65, 0xb8,
	0x2d, 0xba, 0xa2, 0xc4, 0x36, 0x67, 0xae, 0x08, 0x85, 0xed, 0x85, 0x2f, 0x03, 0xc1, 0x90, 0xde,
	0xb3, 0x0e, 0x85, 0xb4, 0xd5, 0x10, 0x21, 0x5b, 0x64, 0x74, 0x3f, 0xaf, 0x86, 0x55, 0xa6, 0xc6,
	0x8c, 0xab, 0x40, 0xa4, 0xb1, 0xa6, 0xf7, 0xed, 0xd9, 0xa5, 0x36, 0xb9, 0x2e, 0xa4, 0x1f, 0x33,
	0x7a, 0xe0, 0xfa, 0xcc, 0x0a, 0xd3, 0x35, 0xd6, 0x88, 0x04, 0xc3, 0x90, 0x1e, 0xda, 0xa5, 0x1a,
	0x31, 0x27, 0xdd, 0x88, 0x30, 0x8d, 0x90, 0x52, 0x77, 0x17, 0xa7, 0xc8, 0x0c, 0x86, 0x11, 0xfa,
	0x2a, 0x95, 0x18, 0x61, 0xac, 0xd3, 0x98, 0x6b, 0x7a, 0x64, 0x9d, 0xff, 0xc4, 0xe4, 0x29, 0x8c,
	0x6a, 0xe8, 0xc6, 0x0f, 0x53, 0xa4, 0x63, 0x1b, 0x6b, 0x83, 0x9b, 0x1a, 0x26, 0x42, 0x9a, 0x62,
	0xd9, 0x88, 0x0f, 0x5c, 0x0d, 0x6b, 0xc8, 0xf4, 0x49, 0x2e, 0x5d, 0xa4, 0x63, 0xd7, 0x27, 0x75,
	0x36, 0xff, 0xd9, 0x82, 0x41, 0xfe, 0xa5, 0x7c, 0x42, 0x79, 0x63, 0x5a, 0x67, 0x0e, 0xf0, 0x01,
	0x57, 0xc5, 0xe7, 0xb3, 0xf9, 0x31, 0x8f, 0x37, 0x11, 0x79, 0x03, 0xbd, 0xf7, 0xa8, 0x73, 0xa5,
	0xc8, 0xe1, 0xc6, 0x0e, 0x37, 0xd3, 0xc6, 0x47, 0x9b, 0xa3, 0xa1, 0xf8, 0xec, 0x5f, 0xc1, 0xa0,
	0x0a, 0xf1, 0x36, 0xbb, 0x38, 0xbb, 0x3b, 0xca, 0x5f, 0x12, 0x78, 0x09, 0xbd, 0x73, 0xc6, 0xf5,
	0x3f, 0xb2, 0xae, 0x45, 0x5b, 0x1b, 0x40, 0xe4, 0x1c, 0xf6, 0xce, 0x30, 0x44, 0x8d, 0xff, 0x75,
	0xf6, 0x9d, 0x61, 0x5e, 0x40, 0xef, 0x73, 0x12, 0x0a, 0x9f, 0xb9, 0x51, 0x55, 0x1b, 0xc6, 0x16,
	0xd4, 0x1d, 0xd7, 0xe6, 0xdd, 0xa2, 0x63, 0xff, 0x04, 0xcf, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff,
	0xa0, 0x23, 0x37, 0x18, 0x24, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductServiceClient interface {
	NewProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*Product, error)
	GetProducts(ctx context.Context, in *ProductParams, opts ...grpc.CallOption) (*ProductResponse, error)
	GetProductByID(ctx context.Context, in *ProductParams, opts ...grpc.CallOption) (*Product, error)
	EditProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*EmptyResponse, error)
	DeleteProductByID(ctx context.Context, in *ProductParams, opts ...grpc.CallOption) (*EmptyResponse, error)
	UploadImage(ctx context.Context, in *Image, opts ...grpc.CallOption) (*ImageResponse, error)
}

type productServiceClient struct {
	cc *grpc.ClientConn
}

func NewProductServiceClient(cc *grpc.ClientConn) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) NewProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, "/products.ProductService/NewProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProducts(ctx context.Context, in *ProductParams, opts ...grpc.CallOption) (*ProductResponse, error) {
	out := new(ProductResponse)
	err := c.cc.Invoke(ctx, "/products.ProductService/GetProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProductByID(ctx context.Context, in *ProductParams, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, "/products.ProductService/GetProductByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) EditProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/products.ProductService/EditProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteProductByID(ctx context.Context, in *ProductParams, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/products.ProductService/DeleteProductByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UploadImage(ctx context.Context, in *Image, opts ...grpc.CallOption) (*ImageResponse, error) {
	out := new(ImageResponse)
	err := c.cc.Invoke(ctx, "/products.ProductService/UploadImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
type ProductServiceServer interface {
	NewProduct(context.Context, *Product) (*Product, error)
	GetProducts(context.Context, *ProductParams) (*ProductResponse, error)
	GetProductByID(context.Context, *ProductParams) (*Product, error)
	EditProduct(context.Context, *Product) (*EmptyResponse, error)
	DeleteProductByID(context.Context, *ProductParams) (*EmptyResponse, error)
	UploadImage(context.Context, *Image) (*ImageResponse, error)
}

// UnimplementedProductServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProductServiceServer struct {
}

func (*UnimplementedProductServiceServer) NewProduct(ctx context.Context, req *Product) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewProduct not implemented")
}
func (*UnimplementedProductServiceServer) GetProducts(ctx context.Context, req *ProductParams) (*ProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProducts not implemented")
}
func (*UnimplementedProductServiceServer) GetProductByID(ctx context.Context, req *ProductParams) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductByID not implemented")
}
func (*UnimplementedProductServiceServer) EditProduct(ctx context.Context, req *Product) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditProduct not implemented")
}
func (*UnimplementedProductServiceServer) DeleteProductByID(ctx context.Context, req *ProductParams) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProductByID not implemented")
}
func (*UnimplementedProductServiceServer) UploadImage(ctx context.Context, req *Image) (*ImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadImage not implemented")
}

func RegisterProductServiceServer(s *grpc.Server, srv ProductServiceServer) {
	s.RegisterService(&_ProductService_serviceDesc, srv)
}

func _ProductService_NewProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Product)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).NewProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/products.ProductService/NewProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).NewProduct(ctx, req.(*Product))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/products.ProductService/GetProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProducts(ctx, req.(*ProductParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProductByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProductByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/products.ProductService/GetProductByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProductByID(ctx, req.(*ProductParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_EditProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Product)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).EditProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/products.ProductService/EditProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).EditProduct(ctx, req.(*Product))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteProductByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteProductByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/products.ProductService/DeleteProductByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteProductByID(ctx, req.(*ProductParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UploadImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Image)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UploadImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/products.ProductService/UploadImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UploadImage(ctx, req.(*Image))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "products.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewProduct",
			Handler:    _ProductService_NewProduct_Handler,
		},
		{
			MethodName: "GetProducts",
			Handler:    _ProductService_GetProducts_Handler,
		},
		{
			MethodName: "GetProductByID",
			Handler:    _ProductService_GetProductByID_Handler,
		},
		{
			MethodName: "EditProduct",
			Handler:    _ProductService_EditProduct_Handler,
		},
		{
			MethodName: "DeleteProductByID",
			Handler:    _ProductService_DeleteProductByID_Handler,
		},
		{
			MethodName: "UploadImage",
			Handler:    _ProductService_UploadImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "products/products.proto",
}
