// Code generated by protoc-gen-go. DO NOT EDIT.
// source: products.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProductParams struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Jwt                  string   `protobuf:"bytes,2,opt,name=jwt,proto3" json:"jwt,omitempty"`
	SortFields           []string `protobuf:"bytes,3,rep,name=sortFields,proto3" json:"sortFields,omitempty"`
	Query                *Query   `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductParams) Reset()         { *m = ProductParams{} }
func (m *ProductParams) String() string { return proto.CompactTextString(m) }
func (*ProductParams) ProtoMessage()    {}
func (*ProductParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{0}
}

func (m *ProductParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductParams.Unmarshal(m, b)
}
func (m *ProductParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductParams.Marshal(b, m, deterministic)
}
func (m *ProductParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductParams.Merge(m, src)
}
func (m *ProductParams) XXX_Size() int {
	return xxx_messageInfo_ProductParams.Size(m)
}
func (m *ProductParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductParams.DiscardUnknown(m)
}

var xxx_messageInfo_ProductParams proto.InternalMessageInfo

func (m *ProductParams) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProductParams) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

func (m *ProductParams) GetSortFields() []string {
	if m != nil {
		return m.SortFields
	}
	return nil
}

func (m *ProductParams) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

type Query struct {
	Querystring          string   `protobuf:"bytes,1,opt,name=Querystring,proto3" json:"Querystring,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{1}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetQuerystring() string {
	if m != nil {
		return m.Querystring
	}
	return ""
}

type ProductResponse struct {
	Products             []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProductResponse) Reset()         { *m = ProductResponse{} }
func (m *ProductResponse) String() string { return proto.CompactTextString(m) }
func (*ProductResponse) ProtoMessage()    {}
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{2}
}

func (m *ProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductResponse.Unmarshal(m, b)
}
func (m *ProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductResponse.Marshal(b, m, deterministic)
}
func (m *ProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductResponse.Merge(m, src)
}
func (m *ProductResponse) XXX_Size() int {
	return xxx_messageInfo_ProductResponse.Size(m)
}
func (m *ProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProductResponse proto.InternalMessageInfo

func (m *ProductResponse) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{3}
}

func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (m *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(m, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

type Product struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Qtyinstock           int32    `protobuf:"varint,2,opt,name=qtyinstock,proto3" json:"qtyinstock,omitempty"`
	Category             string   `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Subcategory          string   `protobuf:"bytes,4,opt,name=subcategory,proto3" json:"subcategory,omitempty"`
	Sector               string   `protobuf:"bytes,5,opt,name=sector,proto3" json:"sector,omitempty"`
	Buyingprice          int32    `protobuf:"varint,6,opt,name=buyingprice,proto3" json:"buyingprice,omitempty"`
	Desiredprofit        int32    `protobuf:"varint,7,opt,name=desiredprofit,proto3" json:"desiredprofit,omitempty"`
	Sellingprice         int32    `protobuf:"varint,8,opt,name=sellingprice,proto3" json:"sellingprice,omitempty"`
	Addedtime            int64    `protobuf:"varint,9,opt,name=addedtime,proto3" json:"addedtime,omitempty"`
	Description          string   `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	Id                   string   `protobuf:"bytes,11,opt,name=id,proto3" json:"id,omitempty"`
	Sizew                float32  `protobuf:"fixed32,12,opt,name=sizew,proto3" json:"sizew,omitempty"`
	Sizel                float32  `protobuf:"fixed32,13,opt,name=sizel,proto3" json:"sizel,omitempty"`
	Sized                float32  `protobuf:"fixed32,14,opt,name=sized,proto3" json:"sized,omitempty"`
	Sizeh                float32  `protobuf:"fixed32,15,opt,name=sizeh,proto3" json:"sizeh,omitempty"`
	Weight               float32  `protobuf:"fixed32,16,opt,name=weight,proto3" json:"weight,omitempty"`
	Userid               string   `protobuf:"bytes,17,opt,name=userid,proto3" json:"userid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{4}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetQtyinstock() int32 {
	if m != nil {
		return m.Qtyinstock
	}
	return 0
}

func (m *Product) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Product) GetSubcategory() string {
	if m != nil {
		return m.Subcategory
	}
	return ""
}

func (m *Product) GetSector() string {
	if m != nil {
		return m.Sector
	}
	return ""
}

func (m *Product) GetBuyingprice() int32 {
	if m != nil {
		return m.Buyingprice
	}
	return 0
}

func (m *Product) GetDesiredprofit() int32 {
	if m != nil {
		return m.Desiredprofit
	}
	return 0
}

func (m *Product) GetSellingprice() int32 {
	if m != nil {
		return m.Sellingprice
	}
	return 0
}

func (m *Product) GetAddedtime() int64 {
	if m != nil {
		return m.Addedtime
	}
	return 0
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetSizew() float32 {
	if m != nil {
		return m.Sizew
	}
	return 0
}

func (m *Product) GetSizel() float32 {
	if m != nil {
		return m.Sizel
	}
	return 0
}

func (m *Product) GetSized() float32 {
	if m != nil {
		return m.Sized
	}
	return 0
}

func (m *Product) GetSizeh() float32 {
	if m != nil {
		return m.Sizeh
	}
	return 0
}

func (m *Product) GetWeight() float32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Product) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func init() {
	proto.RegisterType((*ProductParams)(nil), "proto.ProductParams")
	proto.RegisterType((*Query)(nil), "proto.Query")
	proto.RegisterType((*ProductResponse)(nil), "proto.ProductResponse")
	proto.RegisterType((*EmptyResponse)(nil), "proto.EmptyResponse")
	proto.RegisterType((*Product)(nil), "proto.Product")
}

func init() { proto.RegisterFile("products.proto", fileDescriptor_8c6e54f42122eb82) }

var fileDescriptor_8c6e54f42122eb82 = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0x4f, 0x8f, 0xd3, 0x3c,
	0x10, 0xc6, 0x95, 0xa6, 0xe9, 0xb6, 0xd3, 0x36, 0xdd, 0xb5, 0xaa, 0x95, 0x55, 0xbd, 0x7a, 0x15,
	0x45, 0x1c, 0x02, 0x87, 0x3d, 0x14, 0x89, 0x0b, 0x42, 0x48, 0x68, 0x01, 0x71, 0x41, 0x4b, 0xf8,
	0x04, 0x69, 0x3c, 0xb4, 0x86, 0x34, 0xce, 0xda, 0x0e, 0x55, 0xf8, 0xa2, 0x7c, 0x17, 0x4e, 0x28,
	0x8e, 0xf3, 0xa7, 0x15, 0x88, 0x53, 0x3d, 0xbf, 0x99, 0x27, 0x33, 0x8f, 0x3d, 0x05, 0xbf, 0x90,
	0x82, 0x95, 0xa9, 0x56, 0x77, 0x85, 0x14, 0x5a, 0x10, 0xcf, 0xfc, 0x84, 0x25, 0x2c, 0x1f, 0x9a,
	0xc4, 0x43, 0x22, 0x93, 0xa3, 0x22, 0x3e, 0x8c, 0x38, 0xa3, 0x4e, 0xe0, 0x44, 0xb3, 0x78, 0xc4,
	0x19, 0xb9, 0x06, 0xf7, 0xeb, 0x49, 0xd3, 0x91, 0x01, 0xf5, 0x91, 0xfc, 0x0f, 0xa0, 0x84, 0xd4,
	0xef, 0x38, 0x66, 0x4c, 0x51, 0x37, 0x70, 0xa3, 0x59, 0x3c, 0x20, 0x24, 0x04, 0xef, 0xb1, 0x44,
	0x59, 0xd1, 0x71, 0xe0, 0x44, 0xf3, 0xed, 0xa2, 0x69, 0x78, 0xf7, 0xa9, 0x66, 0x71, 0x93, 0x0a,
	0x9f, 0x82, 0x67, 0x62, 0x12, 0xc0, 0xdc, 0x1c, 0x94, 0x96, 0x3c, 0xdf, 0xdb, 0xbe, 0x43, 0x14,
	0xbe, 0x82, 0x95, 0x9d, 0x30, 0x46, 0x55, 0x88, 0x5c, 0x21, 0x79, 0x06, 0xd3, 0xd6, 0x0d, 0x75,
	0x02, 0x37, 0x9a, 0x6f, 0x7d, 0xdb, 0xa4, 0xad, 0xec, 0xf2, 0xe1, 0x0a, 0x96, 0x6f, 0x8f, 0x85,
	0xae, 0x5a, 0x71, 0xf8, 0xd3, 0x85, 0x2b, 0x5b, 0x46, 0x08, 0x8c, 0xf3, 0xe4, 0x88, 0xb6, 0xad,
	0x39, 0xd7, 0xf6, 0x1e, 0x75, 0xc5, 0x73, 0xa5, 0x45, 0xfa, 0xcd, 0xf8, 0xf6, 0xe2, 0x01, 0x21,
	0x1b, 0x98, 0xa6, 0x89, 0xc6, 0xbd, 0x90, 0x15, 0x75, 0x8d, 0xae, 0x8b, 0x6b, 0x37, 0xaa, 0xdc,
	0x75, 0xe9, 0x71, 0xe3, 0x66, 0x80, 0xc8, 0x2d, 0x4c, 0x14, 0xa6, 0x5a, 0x48, 0xea, 0x99, 0xa4,
	0x8d, 0x6a, 0xe5, 0xae, 0xac, 0x78, 0xbe, 0x2f, 0x24, 0x4f, 0x91, 0x4e, 0x4c, 0xdb, 0x21, 0x22,
	0x4f, 0x60, 0xc9, 0x50, 0x71, 0x89, 0xac, 0x90, 0xe2, 0x0b, 0xd7, 0xf4, 0xca, 0xd4, 0x9c, 0x43,
	0x12, 0xc2, 0x42, 0x61, 0x96, 0x75, 0x1f, 0x9a, 0x9a, 0xa2, 0x33, 0x46, 0xfe, 0x83, 0x59, 0xc2,
	0x18, 0x32, 0xcd, 0x8f, 0x48, 0x67, 0x81, 0x13, 0xb9, 0x71, 0x0f, 0xea, 0x49, 0x18, 0xaa, 0x54,
	0xf2, 0x42, 0x73, 0x91, 0x53, 0x68, 0x3c, 0x0c, 0x90, 0x5d, 0x91, 0x79, 0xb7, 0x22, 0x6b, 0xf0,
	0x14, 0xff, 0x81, 0x27, 0xba, 0x08, 0x9c, 0x68, 0x14, 0x37, 0x41, 0x4b, 0x33, 0xba, 0xec, 0x69,
	0xd6, 0x52, 0x46, 0xfd, 0x9e, 0x76, 0x5f, 0x38, 0xd0, 0x55, 0x4f, 0x0f, 0xf5, 0x5d, 0x9d, 0x90,
	0xef, 0x0f, 0x9a, 0x5e, 0x1b, 0x6c, 0xa3, 0x9a, 0x97, 0x0a, 0x25, 0x67, 0xf4, 0xa6, 0xb9, 0xc3,
	0x26, 0xda, 0xfe, 0x72, 0xc0, 0xb7, 0x2f, 0xfb, 0x19, 0xe5, 0xf7, 0xda, 0xea, 0x16, 0xe0, 0x23,
	0x9e, 0xda, 0xe7, 0xbe, 0xd8, 0x92, 0xcd, 0xda, 0xc6, 0x67, 0x0b, 0x42, 0x5e, 0xc2, 0xfc, 0x3d,
	0x6a, 0x5b, 0xa3, 0xc8, 0xfa, 0x5c, 0xd4, 0xfc, 0x4d, 0x36, 0xb7, 0x17, 0x0b, 0xd7, 0x8a, 0x5f,
	0x80, 0xdf, 0x8b, 0xdf, 0x54, 0x1f, 0xee, 0xff, 0xa2, 0xbf, 0x18, 0x85, 0xbc, 0x86, 0x9b, 0x7b,
	0xcc, 0x50, 0xe3, 0xbf, 0xa5, 0x7f, 0x9c, 0x7a, 0x37, 0x31, 0xf0, 0xf9, 0xef, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xf0, 0x9a, 0x88, 0xd4, 0xe8, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductServiceClient interface {
	NewProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*EmptyResponse, error)
	GetProducts(ctx context.Context, in *ProductParams, opts ...grpc.CallOption) (*ProductResponse, error)
	GetProductByID(ctx context.Context, in *ProductParams, opts ...grpc.CallOption) (*Product, error)
	DeleteProductByID(ctx context.Context, in *ProductParams, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type productServiceClient struct {
	cc *grpc.ClientConn
}

func NewProductServiceClient(cc *grpc.ClientConn) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) NewProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/proto.ProductService/NewProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProducts(ctx context.Context, in *ProductParams, opts ...grpc.CallOption) (*ProductResponse, error) {
	out := new(ProductResponse)
	err := c.cc.Invoke(ctx, "/proto.ProductService/GetProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProductByID(ctx context.Context, in *ProductParams, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, "/proto.ProductService/GetProductByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteProductByID(ctx context.Context, in *ProductParams, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/proto.ProductService/DeleteProductByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
type ProductServiceServer interface {
	NewProduct(context.Context, *Product) (*EmptyResponse, error)
	GetProducts(context.Context, *ProductParams) (*ProductResponse, error)
	GetProductByID(context.Context, *ProductParams) (*Product, error)
	DeleteProductByID(context.Context, *ProductParams) (*EmptyResponse, error)
}

// UnimplementedProductServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProductServiceServer struct {
}

func (*UnimplementedProductServiceServer) NewProduct(ctx context.Context, req *Product) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewProduct not implemented")
}
func (*UnimplementedProductServiceServer) GetProducts(ctx context.Context, req *ProductParams) (*ProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProducts not implemented")
}
func (*UnimplementedProductServiceServer) GetProductByID(ctx context.Context, req *ProductParams) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductByID not implemented")
}
func (*UnimplementedProductServiceServer) DeleteProductByID(ctx context.Context, req *ProductParams) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProductByID not implemented")
}

func RegisterProductServiceServer(s *grpc.Server, srv ProductServiceServer) {
	s.RegisterService(&_ProductService_serviceDesc, srv)
}

func _ProductService_NewProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Product)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).NewProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProductService/NewProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).NewProduct(ctx, req.(*Product))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProductService/GetProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProducts(ctx, req.(*ProductParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProductByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProductByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProductService/GetProductByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProductByID(ctx, req.(*ProductParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteProductByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteProductByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProductService/DeleteProductByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteProductByID(ctx, req.(*ProductParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewProduct",
			Handler:    _ProductService_NewProduct_Handler,
		},
		{
			MethodName: "GetProducts",
			Handler:    _ProductService_GetProducts_Handler,
		},
		{
			MethodName: "GetProductByID",
			Handler:    _ProductService_GetProductByID_Handler,
		},
		{
			MethodName: "DeleteProductByID",
			Handler:    _ProductService_DeleteProductByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "products.proto",
}
