// Code generated by protoc-gen-go. DO NOT EDIT.
// source: quotes.proto

package proto

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_NEW               Status = 0
	Status_SUPPLIER_APPLIED  Status = 1
	Status_SUPPLIER_REJECTED Status = 2
	Status_CLIENT_APPLIED    Status = 3
	Status_CLIENt_REJECTED   Status = 4
)

var Status_name = map[int32]string{
	0: "NEW",
	1: "SUPPLIER_APPLIED",
	2: "SUPPLIER_REJECTED",
	3: "CLIENT_APPLIED",
	4: "CLIENt_REJECTED",
}

var Status_value = map[string]int32{
	"NEW":               0,
	"SUPPLIER_APPLIED":  1,
	"SUPPLIER_REJECTED": 2,
	"CLIENT_APPLIED":    3,
	"CLIENt_REJECTED":   4,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_aa8c397fe3f70398, []int{0}
}

type QuoteResponse struct {
	Quotes               []*Quote `protobuf:"bytes,1,rep,name=quotes,proto3" json:"quotes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuoteResponse) Reset()         { *m = QuoteResponse{} }
func (m *QuoteResponse) String() string { return proto.CompactTextString(m) }
func (*QuoteResponse) ProtoMessage()    {}
func (*QuoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa8c397fe3f70398, []int{0}
}

func (m *QuoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuoteResponse.Unmarshal(m, b)
}
func (m *QuoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuoteResponse.Marshal(b, m, deterministic)
}
func (m *QuoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuoteResponse.Merge(m, src)
}
func (m *QuoteResponse) XXX_Size() int {
	return xxx_messageInfo_QuoteResponse.Size(m)
}
func (m *QuoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuoteResponse proto.InternalMessageInfo

func (m *QuoteResponse) GetQuotes() []*Quote {
	if m != nil {
		return m.Quotes
	}
	return nil
}

type QuoteUpdateParams struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Quote                *Quote   `protobuf:"bytes,2,opt,name=Quote,proto3" json:"Quote,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuoteUpdateParams) Reset()         { *m = QuoteUpdateParams{} }
func (m *QuoteUpdateParams) String() string { return proto.CompactTextString(m) }
func (*QuoteUpdateParams) ProtoMessage()    {}
func (*QuoteUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa8c397fe3f70398, []int{1}
}

func (m *QuoteUpdateParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuoteUpdateParams.Unmarshal(m, b)
}
func (m *QuoteUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuoteUpdateParams.Marshal(b, m, deterministic)
}
func (m *QuoteUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuoteUpdateParams.Merge(m, src)
}
func (m *QuoteUpdateParams) XXX_Size() int {
	return xxx_messageInfo_QuoteUpdateParams.Size(m)
}
func (m *QuoteUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_QuoteUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_QuoteUpdateParams proto.InternalMessageInfo

func (m *QuoteUpdateParams) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *QuoteUpdateParams) GetQuote() *Quote {
	if m != nil {
		return m.Quote
	}
	return nil
}

type QuoteParams struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Jwt                  string   `protobuf:"bytes,2,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuoteParams) Reset()         { *m = QuoteParams{} }
func (m *QuoteParams) String() string { return proto.CompactTextString(m) }
func (*QuoteParams) ProtoMessage()    {}
func (*QuoteParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa8c397fe3f70398, []int{2}
}

func (m *QuoteParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuoteParams.Unmarshal(m, b)
}
func (m *QuoteParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuoteParams.Marshal(b, m, deterministic)
}
func (m *QuoteParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuoteParams.Merge(m, src)
}
func (m *QuoteParams) XXX_Size() int {
	return xxx_messageInfo_QuoteParams.Size(m)
}
func (m *QuoteParams) XXX_DiscardUnknown() {
	xxx_messageInfo_QuoteParams.DiscardUnknown(m)
}

var xxx_messageInfo_QuoteParams proto.InternalMessageInfo

func (m *QuoteParams) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *QuoteParams) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

type QuoteValidationParams struct {
	QuoteID              string   `protobuf:"bytes,1,opt,name=QuoteID,proto3" json:"QuoteID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuoteValidationParams) Reset()         { *m = QuoteValidationParams{} }
func (m *QuoteValidationParams) String() string { return proto.CompactTextString(m) }
func (*QuoteValidationParams) ProtoMessage()    {}
func (*QuoteValidationParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa8c397fe3f70398, []int{3}
}

func (m *QuoteValidationParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuoteValidationParams.Unmarshal(m, b)
}
func (m *QuoteValidationParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuoteValidationParams.Marshal(b, m, deterministic)
}
func (m *QuoteValidationParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuoteValidationParams.Merge(m, src)
}
func (m *QuoteValidationParams) XXX_Size() int {
	return xxx_messageInfo_QuoteValidationParams.Size(m)
}
func (m *QuoteValidationParams) XXX_DiscardUnknown() {
	xxx_messageInfo_QuoteValidationParams.DiscardUnknown(m)
}

var xxx_messageInfo_QuoteValidationParams proto.InternalMessageInfo

func (m *QuoteValidationParams) GetQuoteID() string {
	if m != nil {
		return m.QuoteID
	}
	return ""
}

type UserParams struct {
	Jwt                  string   `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserParams) Reset()         { *m = UserParams{} }
func (m *UserParams) String() string { return proto.CompactTextString(m) }
func (*UserParams) ProtoMessage()    {}
func (*UserParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa8c397fe3f70398, []int{4}
}

func (m *UserParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserParams.Unmarshal(m, b)
}
func (m *UserParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserParams.Marshal(b, m, deterministic)
}
func (m *UserParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserParams.Merge(m, src)
}
func (m *UserParams) XXX_Size() int {
	return xxx_messageInfo_UserParams.Size(m)
}
func (m *UserParams) XXX_DiscardUnknown() {
	xxx_messageInfo_UserParams.DiscardUnknown(m)
}

var xxx_messageInfo_UserParams proto.InternalMessageInfo

func (m *UserParams) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

type Response struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa8c397fe3f70398, []int{5}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetParams struct {
	SortFields           []string `protobuf:"bytes,1,rep,name=sortFields,proto3" json:"sortFields,omitempty"`
	Query                *Query   `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetParams) Reset()         { *m = GetParams{} }
func (m *GetParams) String() string { return proto.CompactTextString(m) }
func (*GetParams) ProtoMessage()    {}
func (*GetParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa8c397fe3f70398, []int{6}
}

func (m *GetParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetParams.Unmarshal(m, b)
}
func (m *GetParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetParams.Marshal(b, m, deterministic)
}
func (m *GetParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetParams.Merge(m, src)
}
func (m *GetParams) XXX_Size() int {
	return xxx_messageInfo_GetParams.Size(m)
}
func (m *GetParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetParams proto.InternalMessageInfo

func (m *GetParams) GetSortFields() []string {
	if m != nil {
		return m.SortFields
	}
	return nil
}

func (m *GetParams) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

type Quote struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	QuotationPrice       float32    `protobuf:"fixed32,2,opt,name=quotationPrice,proto3" json:"quotationPrice,omitempty"`
	Phonenumber          string     `protobuf:"bytes,3,opt,name=phonenumber,proto3" json:"phonenumber,omitempty"`
	Whatsapp             string     `protobuf:"bytes,4,opt,name=whatsapp,proto3" json:"whatsapp,omitempty"`
	Email                string     `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Supplierid           string     `protobuf:"bytes,6,opt,name=supplierid,proto3" json:"supplierid,omitempty"`
	Products             []*Product `protobuf:"bytes,7,rep,name=products,proto3" json:"products,omitempty"`
	Jwt                  string     `protobuf:"bytes,9,opt,name=jwt,proto3" json:"jwt,omitempty"`
	Name                 string     `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	City                 string     `protobuf:"bytes,11,opt,name=city,proto3" json:"city,omitempty"`
	Address              string     `protobuf:"bytes,12,opt,name=address,proto3" json:"address,omitempty"`
	Zip                  string     `protobuf:"bytes,13,opt,name=zip,proto3" json:"zip,omitempty"`
	Size                 string     `protobuf:"bytes,14,opt,name=size,proto3" json:"size,omitempty"`
	Userid               string     `protobuf:"bytes,15,opt,name=userid,proto3" json:"userid,omitempty"`
	Status               Status     `protobuf:"varint,16,opt,name=status,proto3,enum=proto.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Quote) Reset()         { *m = Quote{} }
func (m *Quote) String() string { return proto.CompactTextString(m) }
func (*Quote) ProtoMessage()    {}
func (*Quote) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa8c397fe3f70398, []int{7}
}

func (m *Quote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quote.Unmarshal(m, b)
}
func (m *Quote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quote.Marshal(b, m, deterministic)
}
func (m *Quote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quote.Merge(m, src)
}
func (m *Quote) XXX_Size() int {
	return xxx_messageInfo_Quote.Size(m)
}
func (m *Quote) XXX_DiscardUnknown() {
	xxx_messageInfo_Quote.DiscardUnknown(m)
}

var xxx_messageInfo_Quote proto.InternalMessageInfo

func (m *Quote) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Quote) GetQuotationPrice() float32 {
	if m != nil {
		return m.QuotationPrice
	}
	return 0
}

func (m *Quote) GetPhonenumber() string {
	if m != nil {
		return m.Phonenumber
	}
	return ""
}

func (m *Quote) GetWhatsapp() string {
	if m != nil {
		return m.Whatsapp
	}
	return ""
}

func (m *Quote) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Quote) GetSupplierid() string {
	if m != nil {
		return m.Supplierid
	}
	return ""
}

func (m *Quote) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *Quote) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

func (m *Quote) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Quote) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Quote) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Quote) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *Quote) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *Quote) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func (m *Quote) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_NEW
}

func init() {
	proto.RegisterEnum("proto.Status", Status_name, Status_value)
	proto.RegisterType((*QuoteResponse)(nil), "proto.QuoteResponse")
	proto.RegisterType((*QuoteUpdateParams)(nil), "proto.QuoteUpdateParams")
	proto.RegisterType((*QuoteParams)(nil), "proto.QuoteParams")
	proto.RegisterType((*QuoteValidationParams)(nil), "proto.QuoteValidationParams")
	proto.RegisterType((*UserParams)(nil), "proto.UserParams")
	proto.RegisterType((*Response)(nil), "proto.Response")
	proto.RegisterType((*GetParams)(nil), "proto.GetParams")
	proto.RegisterType((*Quote)(nil), "proto.Quote")
}

func init() { proto.RegisterFile("quotes.proto", fileDescriptor_aa8c397fe3f70398) }

var fileDescriptor_aa8c397fe3f70398 = []byte{
	// 627 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x71, 0x93, 0x26, 0x93, 0xc4, 0x75, 0x86, 0x16, 0xad, 0x22, 0x54, 0x45, 0x16, 0xa0,
	0xd2, 0x43, 0x81, 0x54, 0x70, 0x42, 0x48, 0xb4, 0x36, 0x95, 0x51, 0x55, 0x82, 0xdb, 0xc2, 0x11,
	0xb9, 0xf5, 0x8a, 0x2e, 0x4a, 0x62, 0xd7, 0xbb, 0xa6, 0x4a, 0x1f, 0x81, 0x27, 0xe0, 0x71, 0xd1,
	0xfe, 0xd8, 0x75, 0x13, 0x7a, 0xf2, 0xce, 0xf7, 0xcd, 0x37, 0x3b, 0x33, 0x3b, 0x63, 0xe8, 0x5d,
	0x17, 0xa9, 0xa0, 0x7c, 0x2f, 0xcb, 0x53, 0x91, 0x62, 0x53, 0x7d, 0x86, 0x4e, 0x96, 0xa7, 0x49,
	0x71, 0x29, 0x0c, 0xec, 0xbd, 0x85, 0xfe, 0x57, 0xe9, 0x16, 0x51, 0x9e, 0xa5, 0x73, 0x4e, 0xf1,
	0x19, 0xb4, 0xb4, 0x8e, 0x58, 0x23, 0x7b, 0xa7, 0x3b, 0xee, 0x69, 0xc7, 0x3d, 0xed, 0x65, 0x38,
	0xef, 0x08, 0x06, 0x0a, 0x38, 0xcf, 0x92, 0x58, 0xd0, 0x49, 0x9c, 0xc7, 0x33, 0x8e, 0x0e, 0x34,
	0x42, 0x9f, 0x58, 0x23, 0x6b, 0xa7, 0x13, 0x35, 0x42, 0x1f, 0x3d, 0x68, 0x2a, 0x27, 0xd2, 0x18,
	0x59, 0x2b, 0x91, 0x34, 0xe5, 0xbd, 0x82, 0xae, 0x3a, 0x3c, 0x10, 0xc2, 0x05, 0xfb, 0xd7, 0x8d,
	0x50, 0x01, 0x3a, 0x91, 0x3c, 0x7a, 0x6f, 0x60, 0x4b, 0x09, 0xbe, 0xc5, 0x53, 0x96, 0xc4, 0x82,
	0xa5, 0x73, 0x23, 0x25, 0xb0, 0xae, 0x88, 0x4a, 0x5f, 0x9a, 0xde, 0x36, 0xc0, 0x39, 0xa7, 0xb9,
	0xf1, 0x33, 0x21, 0xad, 0xbb, 0x90, 0x43, 0x68, 0x57, 0xe5, 0x3b, 0xd0, 0x60, 0x49, 0x99, 0x00,
	0x4b, 0xbc, 0x2f, 0xd0, 0x39, 0xa2, 0xc2, 0x48, 0xb7, 0x01, 0x78, 0x9a, 0x8b, 0x4f, 0x8c, 0x4e,
	0x13, 0xdd, 0x9f, 0x4e, 0x54, 0x43, 0x64, 0xc1, 0xd7, 0x05, 0xcd, 0x17, 0x2b, 0x05, 0xd3, 0x7c,
	0x11, 0x69, 0xca, 0xfb, 0x6b, 0x9b, 0xae, 0x2c, 0x5f, 0x85, 0x2f, 0xc0, 0x91, 0xdd, 0xd5, 0x35,
	0xe5, 0xec, 0x52, 0xf7, 0xad, 0x11, 0x2d, 0xa1, 0x38, 0x82, 0x6e, 0x76, 0x95, 0xce, 0xe9, 0xbc,
	0x98, 0x5d, 0xd0, 0x9c, 0xd8, 0x2a, 0x40, 0x1d, 0xc2, 0x21, 0xb4, 0x6f, 0xae, 0x62, 0xc1, 0xe3,
	0x2c, 0x23, 0x6b, 0x8a, 0xae, 0x6c, 0xdc, 0x84, 0x26, 0x9d, 0xc5, 0x6c, 0x4a, 0x9a, 0x8a, 0xd0,
	0x86, 0xaa, 0xac, 0xc8, 0xb2, 0x29, 0xa3, 0x39, 0x4b, 0x48, 0x4b, 0x51, 0x35, 0x04, 0x77, 0xa1,
	0x5d, 0x0e, 0x0e, 0x59, 0x57, 0x73, 0xe1, 0x98, 0xe2, 0x26, 0x1a, 0x8e, 0x2a, 0xbe, 0x6c, 0x70,
	0xa7, 0x6a, 0x30, 0x22, 0xac, 0xcd, 0xe3, 0x19, 0x25, 0xa0, 0x20, 0x75, 0x96, 0xd8, 0x25, 0x13,
	0x0b, 0xd2, 0xd5, 0x98, 0x3c, 0xcb, 0x27, 0x8c, 0x93, 0x24, 0xa7, 0x9c, 0x93, 0x9e, 0x7e, 0x42,
	0x63, 0xca, 0x98, 0xb7, 0x2c, 0x23, 0x7d, 0x1d, 0xf3, 0x96, 0x65, 0x52, 0xcf, 0xd9, 0x2d, 0x25,
	0x8e, 0xd6, 0xcb, 0x33, 0x3e, 0x81, 0x56, 0xc1, 0x55, 0x05, 0x1b, 0x0a, 0x35, 0x16, 0x3e, 0x87,
	0x16, 0x17, 0xb1, 0x28, 0x38, 0x71, 0x47, 0xd6, 0x8e, 0x33, 0xee, 0x9b, 0xdc, 0x4f, 0x15, 0x18,
	0x19, 0x72, 0xf7, 0x27, 0xb4, 0x34, 0x82, 0xeb, 0x60, 0x9f, 0x04, 0xdf, 0xdd, 0x47, 0xb8, 0x09,
	0xee, 0xe9, 0xf9, 0x64, 0x72, 0x1c, 0x06, 0xd1, 0x8f, 0x8f, 0xea, 0xeb, 0xbb, 0x16, 0x6e, 0xc1,
	0xa0, 0x42, 0xa3, 0xe0, 0x73, 0x70, 0x78, 0x16, 0xf8, 0x6e, 0x03, 0x11, 0x9c, 0xc3, 0xe3, 0x30,
	0x38, 0x39, 0xab, 0x5c, 0x6d, 0x7c, 0x0c, 0x1b, 0x0a, 0x13, 0x77, 0x8e, 0x6b, 0xe3, 0x3f, 0x36,
	0xf4, 0xd4, 0x0c, 0x9c, 0xd2, 0xfc, 0xb7, 0x7c, 0xd2, 0x97, 0xd0, 0x3e, 0xa1, 0x37, 0x7a, 0x2c,
	0xee, 0xad, 0xc9, 0x70, 0xc3, 0x58, 0xd5, 0x80, 0xee, 0xab, 0x81, 0x54, 0x24, 0x47, 0xd7, 0xb0,
	0xd5, 0x88, 0x0e, 0x37, 0xef, 0x2d, 0x59, 0x29, 0x7a, 0x0d, 0xbd, 0x52, 0x74, 0xb0, 0x08, 0x7d,
	0xc4, 0xba, 0x97, 0x51, 0xde, 0xbb, 0x17, 0x3f, 0x40, 0xdf, 0x6c, 0x18, 0xd5, 0xc0, 0xd3, 0x3a,
	0xbd, 0xbc, 0x7c, 0xab, 0x69, 0xbe, 0x87, 0x41, 0x95, 0xe6, 0xc1, 0x42, 0xae, 0x5f, 0xe8, 0xe3,
	0xc0, 0x78, 0xdd, 0x6d, 0xe3, 0x03, 0xf9, 0x8e, 0xa1, 0xeb, 0xd3, 0x29, 0x2d, 0xef, 0xfe, 0x5f,
	0xba, 0x2b, 0x37, 0xbe, 0x83, 0x4e, 0x90, 0x30, 0x7d, 0x25, 0x92, 0xba, 0xa2, 0xfe, 0x93, 0x5a,
	0xd1, 0x5d, 0xb4, 0x94, 0xbd, 0xff, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xdf, 0x71, 0x36, 0x2f,
	0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QuoteServiceClient is the client API for QuoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QuoteServiceClient interface {
	NewQuote(ctx context.Context, in *Quote, opts ...grpc.CallOption) (*Response, error)
	GetQuotes(ctx context.Context, in *GetParams, opts ...grpc.CallOption) (*QuoteResponse, error)
	GetQuoteByID(ctx context.Context, in *QuoteParams, opts ...grpc.CallOption) (*Quote, error)
	ValidateQuote(ctx context.Context, in *QuoteValidationParams, opts ...grpc.CallOption) (*Response, error)
	GetQuotesByUserID(ctx context.Context, in *UserParams, opts ...grpc.CallOption) (*QuoteResponse, error)
	DeleteQuote(ctx context.Context, in *QuoteParams, opts ...grpc.CallOption) (*Response, error)
	EditQuote(ctx context.Context, in *QuoteUpdateParams, opts ...grpc.CallOption) (*Response, error)
}

type quoteServiceClient struct {
	cc *grpc.ClientConn
}

func NewQuoteServiceClient(cc *grpc.ClientConn) QuoteServiceClient {
	return &quoteServiceClient{cc}
}

func (c *quoteServiceClient) NewQuote(ctx context.Context, in *Quote, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.QuoteService/NewQuote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) GetQuotes(ctx context.Context, in *GetParams, opts ...grpc.CallOption) (*QuoteResponse, error) {
	out := new(QuoteResponse)
	err := c.cc.Invoke(ctx, "/proto.QuoteService/GetQuotes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) GetQuoteByID(ctx context.Context, in *QuoteParams, opts ...grpc.CallOption) (*Quote, error) {
	out := new(Quote)
	err := c.cc.Invoke(ctx, "/proto.QuoteService/GetQuoteByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) ValidateQuote(ctx context.Context, in *QuoteValidationParams, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.QuoteService/ValidateQuote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) GetQuotesByUserID(ctx context.Context, in *UserParams, opts ...grpc.CallOption) (*QuoteResponse, error) {
	out := new(QuoteResponse)
	err := c.cc.Invoke(ctx, "/proto.QuoteService/GetQuotesByUserID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) DeleteQuote(ctx context.Context, in *QuoteParams, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.QuoteService/DeleteQuote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) EditQuote(ctx context.Context, in *QuoteUpdateParams, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.QuoteService/EditQuote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuoteServiceServer is the server API for QuoteService service.
type QuoteServiceServer interface {
	NewQuote(context.Context, *Quote) (*Response, error)
	GetQuotes(context.Context, *GetParams) (*QuoteResponse, error)
	GetQuoteByID(context.Context, *QuoteParams) (*Quote, error)
	ValidateQuote(context.Context, *QuoteValidationParams) (*Response, error)
	GetQuotesByUserID(context.Context, *UserParams) (*QuoteResponse, error)
	DeleteQuote(context.Context, *QuoteParams) (*Response, error)
	EditQuote(context.Context, *QuoteUpdateParams) (*Response, error)
}

// UnimplementedQuoteServiceServer can be embedded to have forward compatible implementations.
type UnimplementedQuoteServiceServer struct {
}

func (*UnimplementedQuoteServiceServer) NewQuote(ctx context.Context, req *Quote) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewQuote not implemented")
}
func (*UnimplementedQuoteServiceServer) GetQuotes(ctx context.Context, req *GetParams) (*QuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuotes not implemented")
}
func (*UnimplementedQuoteServiceServer) GetQuoteByID(ctx context.Context, req *QuoteParams) (*Quote, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuoteByID not implemented")
}
func (*UnimplementedQuoteServiceServer) ValidateQuote(ctx context.Context, req *QuoteValidationParams) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateQuote not implemented")
}
func (*UnimplementedQuoteServiceServer) GetQuotesByUserID(ctx context.Context, req *UserParams) (*QuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuotesByUserID not implemented")
}
func (*UnimplementedQuoteServiceServer) DeleteQuote(ctx context.Context, req *QuoteParams) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteQuote not implemented")
}
func (*UnimplementedQuoteServiceServer) EditQuote(ctx context.Context, req *QuoteUpdateParams) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditQuote not implemented")
}

func RegisterQuoteServiceServer(s *grpc.Server, srv QuoteServiceServer) {
	s.RegisterService(&_QuoteService_serviceDesc, srv)
}

func _QuoteService_NewQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Quote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).NewQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.QuoteService/NewQuote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).NewQuote(ctx, req.(*Quote))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_GetQuotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).GetQuotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.QuoteService/GetQuotes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).GetQuotes(ctx, req.(*GetParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_GetQuoteByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).GetQuoteByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.QuoteService/GetQuoteByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).GetQuoteByID(ctx, req.(*QuoteParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_ValidateQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteValidationParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).ValidateQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.QuoteService/ValidateQuote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).ValidateQuote(ctx, req.(*QuoteValidationParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_GetQuotesByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).GetQuotesByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.QuoteService/GetQuotesByUserID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).GetQuotesByUserID(ctx, req.(*UserParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_DeleteQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).DeleteQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.QuoteService/DeleteQuote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).DeleteQuote(ctx, req.(*QuoteParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_EditQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).EditQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.QuoteService/EditQuote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).EditQuote(ctx, req.(*QuoteUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _QuoteService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.QuoteService",
	HandlerType: (*QuoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewQuote",
			Handler:    _QuoteService_NewQuote_Handler,
		},
		{
			MethodName: "GetQuotes",
			Handler:    _QuoteService_GetQuotes_Handler,
		},
		{
			MethodName: "GetQuoteByID",
			Handler:    _QuoteService_GetQuoteByID_Handler,
		},
		{
			MethodName: "ValidateQuote",
			Handler:    _QuoteService_ValidateQuote_Handler,
		},
		{
			MethodName: "GetQuotesByUserID",
			Handler:    _QuoteService_GetQuotesByUserID_Handler,
		},
		{
			MethodName: "DeleteQuote",
			Handler:    _QuoteService_DeleteQuote_Handler,
		},
		{
			MethodName: "EditQuote",
			Handler:    _QuoteService_EditQuote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "quotes.proto",
}
